### ISSUE TITLE
Devices are not added, only two buttons

### ISSUE THREAD

**Issue by elmocito** [ebaauw/homebridge-deconz#1]
- When trying to add two bridges only two buttons are shown (see screenshots)
- Second screenshot shows the homebridge message
- homebridge-hue is installed in parallel

![image](https://user-images.githubusercontent.com/42518790/149398268-dafbd5b5-15e4-42f9-8364-22b8fbe17520.png)
![image](https://user-images.githubusercontent.com/42518790/149398375-dc51ae16-6059-4941-9949-02a61ebffcd9.png)

Bug? 🐞

**Comment by elmocito** [comment]
Additional notes:
Now I tried something different.
Although I am pressing the API button it throws an error and the port seems to be wrong...
![image](https://user-images.githubusercontent.com/42518790/149403569-97d8bf84-7bca-487d-be20-2cc23a350767.png)

**Comment by ebaauw** [comment]
> When trying to add two bridges only two buttons are shown (see screenshots)

Yes, see release notes, readme, wiki.

> Although I am pressing the API button it throws an error and the port seems to be wrong...

443 is the default port for the web socket.  Homebridge deCONZ tries to open it, hoping to be lucky.  Once it has connected to the gateway, it retrieves the actual port used by the web socket, and updates the web socket client.  However there’s a typo in the code handling the new port, causing the TypeError, which, in turn, aborts the initialisation.

Homebridge deCONZ did obtain an API key, as the firmware for the Zigbee device was retrieved, and also from the stale API key warnings.  Apart from not receiving events, I think Homebridge deCONZ is working.  Did you look at the gateway accessories in Eve or another HomeKit app?

**Comment by elmocito** [comment]
I start to understand the concept (notes, readme, wiki) and it is finding now the lights, sensor buttons - BUT, it is not finding new devices.
Because of no support?!
![image](https://user-images.githubusercontent.com/42518790/149474432-5dc61c9b-105a-467a-a554-d139fe8d4fdb.png)

**Comment by ebaauw** [comment]
> BUT, it is not finding new devices.

You mean devices newly added to deCONZ?  The should be found when Homebridge deCONZ next polls the gateway, and when the device type is enabled, they should appear in HomeKit (still as a dummy button).

**Comment by elmocito** [comment]
They do, after I tried to add more devices.
But they appear only as dummy buttons and don't show any devices.
Seems to be unsupported devices (see above) - is this relevant?

**Comment by ebaauw** [comment]
I haven’t yet implemented any functional devices yet, see the documentation.  I want to make sure the technical setup works as intended, without errors or wrongly disappearing accessories.

**Comment by elmocito** [comment]
Okay, understood.
Please note that I cannot find the gateway anymore after I have deleted it from HomeKit 🤷🏻‍♂️
But that is a seperate issue. Will close this for now, because everything was clarified. Thanks!
