### ISSUE TITLE
Warning in HB

### ISSUE THREAD

**Issue by mrvocalplay** [ebaauw/homebridge-deconz#102]
My HB Log gives me this warning very often. In the Link they say I should send it to the plugin dev.

[homebridge-deconz] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

**Comment by ebaauw** [comment]
Please capture and attach a debug log file and also attach the debug dump file.
