### ISSUE TITLE
version 0.1.3 - ui error messages

### ISSUE THREAD

**Issue by BEskandari** [ebaauw/homebridge-deconz#106]
After updating to version 0.1.3 I get the below messages by trying to execute ui

pi@homebridge:/var/lib/homebridge $ **ui**
**/usr/local/bin/ui: line 29: json: command not found
ui: /var/lib/homebridge/config.json: cannot find deCONZ platform**

**Comment by ebaauw** [comment]
`json` comes with homebridge-lib, but it's only installed to `/usr/local/bin` when you install homebridge-lib separately.  You can manually install homebridge-lib:
```
sudo npm -g i homebridge-lib
```
However, unless you whitelist plugins in config.json, Homebridge will complain it's not a plugin.

Alternatively, create a symlink to the installation under Homebridge deCONZ:
```
sudo chmod 755 /usr/local/lib/node_modules/homebridge-deconz/lib/homebridge-lib/cli/json.js
sudo ln -s /usr/local/lib/node_modules/homebridge-deconz/lib/homebridge-lib/cli/json.js /usr/local/bin/json
```

**Comment by ebaauw** [comment]
Note to self: instead of `bash` script, create proper JavaScript command, using `JsonFormatter` instead of `json` command.
