### ISSUE TITLE
Phoscon-GW: warning: potentially stale api key

### ISSUE THREAD

**Issue by HomebridgeX** [ebaauw/homebridge-deconz#108]
Hello,

at every startup the following message appears 2x in the log.
How can I reset this message? 

[deCONZ] Phoscon-GW: warning: potentially stale api key: {"create date":"2023-01-14T11:45:12","last use date":"2023-01-14T12:13:23","name":"homebridge-deconz#homebridge"}

Thank you very much!

**Comment by ebaauw** [comment]
See #22.
