### ISSUE TITLE
timesOpened should be instanced with 0

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#111]
Characteristic timesOpened is according to cachedAccessories instanced with value null which leads to warning:

[homebridge-deconz] This plugin generated a warning from the characteristic 'Times Opened': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

I believe timesOpened should be instanced to 0 the first time.

Additionally the characteristic is added to the motion sensor service, but I would presume it should be added to contact sensor service.

**Comment by ebaauw** [comment]
Is this the Samsung multi-sensor from #98?

**Comment by torandreroland** [comment]
See part of comment in #98:

_I don't believe Contact Sensor is the primary service (or ever was). At least the json says "primary": "01-FC02" which is the ZHAVibration resource which I believe is the basis for a motion sensor service (ZHATemperature I assume is the basis for Temperature Sensor service and ZHAOpenClose should be the basis for Contact Sensor service)._

**Comment by ebaauw** [comment]
Not sure if the message was the result of _Times Opened_ being added to the wrong service, or due to initialisation, but it never hurts to initialise it explicitly.

**Comment by torandreroland** [comment]
Observed the times opened characteristic in beta v0.1.5-0. It is still added to the motion sensor service instead of the contact sensor. Additionally it isn't updated anymore when opening/closing the contact sensor.

I don't know if this is due to some migration issue from the old to the new characteristic, but I noticed this in the logging when restarting the first time after updating to beta v0.1.5-0 (for all such contact sensors):

Home Office Window Sensor: remove stale characteristic Times Opened
Home Office Window Sensor: remove stale value timesOpened

**Comment by ebaauw** [comment]
> Observed the times opened characteristic in beta v0.1.5-0. It is still added to the motion sensor service instead of the contact sensor. Additionally it isn't updated anymore when opening/closing the contact sensor.

How long after restarting Homebridge did you see this?  HomeKit doesn't like configuration changes, and it might take a couple of minutes before the changes are reflected in HomeKit.

Does the issue still occur after a while?  And after un-exposing and re-exposing the sensor?

If so, please attached the `cachedAccessories` file for this Homebridge instance.

The messages indicate that Homebridge deCONZ is cleaning up stale characteristics - I would hope from the _Motion Sensor_.

**Comment by ebaauw** [comment]
Fixed in v0.1.5.

**Comment by torandreroland** [comment]
I can confirm that the characteristic is successfully added to the contact sensor and it's being updated as well.

This was tested on version 0.1.7, but it may be that I just didn't allow enough time for the changes to be reflected in HomeKit.

Closing this issue. Thank you for your help!
