### ISSUE TITLE
Unknown device: CLIP-Sensor PUSHDIM-TOOGLE

### ISSUE THREAD

**Issue by TinyMito** [ebaauw/homebridge-deconz#114]
Hi, I have a strange device shows up on HomeKit and this is my current up:

- Pi4B
- Homebridge (extra package deCONZ)
- ConBee II
- Homebridge plugin homebridge-deconz

I have 3 IKEA lights and 2 remote switches all expose properly on Homekit but I do not know where is this **CLIP-Sensor PUSHDIM-TOOGLE** came from.

<img width="176" alt="20230215_000062" src="https://user-images.githubusercontent.com/75095713/219176865-4f646d1c-7da2-43f2-9096-309aedb21869.png">

<img width="542" alt="20230215_000063" src="https://user-images.githubusercontent.com/75095713/219176909-8bad994a-163f-47e5-ab1c-2cd72260239f.png">

<img width="525" alt="20230215_000064" src="https://user-images.githubusercontent.com/75095713/219176938-2e22ea76-18ad-40d9-9b10-e646daf60278.png">

<img width="526" alt="20230215_000065" src="https://user-images.githubusercontent.com/75095713/219176989-f1e8fd67-9890-4ad4-9aa3-36dde31d4cd4.png">

My suspicion would be this device:

<img width="741" alt="20230215_000068" src="https://user-images.githubusercontent.com/75095713/219200082-0b630eef-e176-40c7-a1e0-637f9be9a637.png">

**Comment by ebaauw** [comment]
No, it’s for the CLIPGenericFlag virtual sensor at `/sensors/4`.

**Comment by TinyMito** [comment]
Hi, I just updated the post.

What is the CLIPGenericFlag virtual sensor designed for? Is it possible to remove or exclude that?

**Comment by ebaauw** [comment]
Basically it’s just a variable on the deCONZ API.  It looks like Phoscon created it to keep state for some automation.

You can unexpose it through dynamic dynamic configuration, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.

**Comment by TinyMito** [comment]
Thank you!
