### ISSUE TITLE
Version number in releases different than npm version

### ISSUE THREAD

**Issue by wmutschl** [ebaauw/homebridge-deconz#119]
I just noticed that under [releases](https://github.com/ebaauw/homebridge-deconz/releases) the version number jumped from `v0.1.3` to `v1.0.4` and `v1.0.7`, while the npm version or the plugin version in Homebridge states `homebridge-deconz v0.1.7`. Is this the way it is intended?

**Comment by ebaauw** [comment]
Latest release is v1.0.7, in releases, on npm, and on Discord.  What’s the issue?

**Comment by wmutschl** [comment]
I see it differently:
![Screenshot 2023-02-22 at 13 03 02](https://user-images.githubusercontent.com/36013296/220614675-57aa2a59-5883-4935-bff1-2f9b30c19ef5.png)

**Comment by wmutschl** [comment]
https://www.npmjs.com/package/homebridge-deconz

**Comment by ebaauw** [comment]
Indeed, my latent dyslexia kicks in: it’s v0.1.7

**Comment by ebaauw** [comment]
And now v0.1.9.
