### ISSUE TITLE
Phoscon-GW Button: Programmable Switch Event: Single Press LOG every minute :-(

### ISSUE THREAD

**Issue by MadMacMad** [ebaauw/homebridge-deconz#121]
hello,
where can i'll disable this log message now ?
In latest EVE app impossible now...
why is there this message fired every minute or more often?
<img width="868" alt="Bildschirm­foto 2023-03-07 um 06 48 20" src="https://user-images.githubusercontent.com/10008614/223332059-d3bed5ac-6576-41cb-a05f-8255c3adc7b8.png">

is there no way to disable it?
also noticed that the USB stick sucks lot of Energy and the last driver for PI uses also lot of Processpower...
i'll noticed a change from before firmware to last... 
all is working well except the Deconz USB Stick & driver in Homebridge
thx

**Comment by JanLp** [comment]
https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration

https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#update-gateway-settings

**Comment by BlackDiceagain** [comment]
how and where can i program it? I have this in the homebridge configuration under "accessories": "periodicEvents": false,
written but that doesn't work. so I guess that's not right

**Comment by jakubkasparek** [comment]
@MadMacMad  @BlackDiceagain  did you work it out somehow? The wiki link doesn't help me much.
