### ISSUE TITLE
Tuya Soil Sensor

### ISSUE THREAD

**Issue by BEskandari** [ebaauw/homebridge-deconz#123]
Is it possible to support the Tuya Soil Sensor by displaying also the ZHAMoisture ? For the time being I am able to see only the ZHATemperature.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6731#issuecomment-1489183257

**Comment by ebaauw** [comment]
Do they indeed report `state/moisture` in units of 0.01%, as per the Zigbee spec?  So values from 0 to 10000 for 0% to 100%.

**Comment by BEskandari** [comment]
This is the resources reported by Deconz API:
Keep in mind that for the time being the moisture value is not correct. As you mention we might need to multiply the value by 10000. Because as of now the value is displayed without any coefficient, and it correspond to the value of 32% of another moisture sensor.

{
    "config": {
        "battery": 100,
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "etag": "a0b710211ab1ceed84b223a5a77d233c",
    "lastannounced": null,
    "lastseen": "2023-03-30T21:05Z",
    "manufacturername": "_TZE200_myd45weu",
    "modelid": "TS0601",
    "name": "Moisture 21",
    "state": {
        "lastupdated": "2023-03-30T21:01:21.331",
        "moisture": 28
    },
    "type": "ZHAMoisture",
    "uniqueid": "a4:c1:38:af:22:d1:cc:76-01-0408"
}

**Comment by ebaauw** [comment]
In v0.1.11.  Note that Homebridge deCONZ expects `state/moisture` to be in units of 0.01% (just like `state.humidity`).

**Comment by BEskandari** [comment]
Hi Erik, thanks it is working now with the latest version, I have the moisture in the Eve App.
