### ISSUE TITLE
IKEA GU10 ws 400lm paired with deconz but not seen on homebridge

### ISSUE THREAD

**Issue by Master-Lo** [ebaauw/homebridge-deconz#124]
I have Deconz installed on a Raspberry Pi running a RaspBee 2.

I have various IKEA and hue bulbs but x2 IKEA bulbs TRADFRI bulb GU10 WS 400lm used to work on homebridge hue but have had issues since moving over to homebridge-deconz.

they appear in Deconz GUI but not in homebridge accessory list.

I have tried updating the bulbs firmware via otau in Deconz to the latest version but still the same issue. Could this be a bug in Homebridge-Deconz? So opening issue here to start exploring if it is or if it is something else.

![D0B36342-61DD-4771-9493-1DB8C67DB4AB](https://user-images.githubusercontent.com/129599648/229289417-4f70d38d-bcec-4208-9c67-7223f20dc2f4.jpeg)

**Comment by ebaauw** [comment]
Check Homebridge deCONZ’ dump file to see whether the deCONZ API exposes these lights.  Check the Homebridge log, to check what accessories Homebridge deCONZ exposes.  Use the dynamic configuration to change which devices Homebridge deCONZ exposes as HomeKit accessories, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.  By default Homebridge deCONZ should automatically expose new Zigbee devices, but if you upgraded from an older version, it might not automatically expose devices already identified by the older version.

**Comment by Master-Lo** [comment]
Hey @ebaauw,

Thanks for the push to remind me about updating here.

I found time to try this last night. And with your links found that indeed those individual lights were set to not exposed.

After changing via rest api it now works

Thanks for the help.
