### ISSUE TITLE
Hide individual resources?

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-deconz#125]
Good morning Erik,

I am still in the process of re-setting up my Homekit and need your help again. Unfortunately I couldn't find anything about it anywhere or I didn't understand it.

Is it no longer possible with homebridge-deconz hide individual resources from a device.

I would like to have certain devices, for example, the temperature sensor is not transferred to Homekit to not have too many temperature sensors in a room?
With homebridge-hue it worked via the resource links.

Best regards

**Comment by ebaauw** [comment]
Still on the TODO list: more elaborate dynamic configuration settings, per device resource, or even per button for stateless switches.

**Comment by Nastras** [comment]
Good to know it's on the todo list. Would it be possible that you share your next planned steps (TODO list) for the plugin with us? I think that would reduce any queries about special functions. Thank you!

**Comment by ebaauw** [comment]
I'm afraid that wouldn't be possible, as i don't have a plan nor roadmap.  This is a hobby, and I pickup stuff when I happen to have spare time and I feel like it.  The only documentation I keep are the open issues with the _enhancement_ label.

**Comment by Nastras** [comment]
Can understand you. Thank you!

**Comment by ebaauw** [comment]
As discussed on Discord, for now, I'm introducing `blacklist` and `splitlight` resource links to Homebridge deCONZ, as was done for Homebridge Hue, see https://github.com/ebaauw/homebridge-hue/wiki/Resource-Links.  These should work the same as under Homebridge Hue.  Of course, the name needs to be `homebridge-deconz` and you need the deCONZ API to maintain these.

Note that the functionality for other types of resource links in Homebridge Hue is already handled in Homebridge deCONZ' dynamic configuration, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.

Please try beta v1.0.16-0.  Homebridge deCONZ should react in runtime to these resource links being updated.  If not, you might need to restart Homebrdige deCONZ and/or un-expose and re-expose the corresponding devices.

**Comment by ebaauw** [comment]
I changed `splitlight` to `splitdevice`, allowing `sensors` resources to be split off as well.

**Comment by ebaauw** [comment]
In v1.0.16.
