### ISSUE TITLE
Wall Switch error message: option --json: is unknown

### ISSUE THREAD

**Issue by xBilyz3** [ebaauw/homebridge-deconz#126]
Unfortunately I get this error message. Maybe someone can help me. Could not find the solution myself.

curl -s -X PUT --json ‘{“wallSwitch: true“}’ http://127.0.0.1:46237/gateways/00212EFFFF06A0F1/accessories/7CB03EAA00AF52C0/settings
curl: option --json: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

<img width="1523" alt="Screenshot 2023-04-02 at 11 06 21" src="https://user-images.githubusercontent.com/52658352/229343551-7ab55ba6-4854-42c5-a4dc-cfa09d32f3b8.png">

_Originally posted by @xBilyz3 in https://github.com/ebaauw/homebridge-deconz/issues/91#issuecomment-1493274540_

**Comment by BEskandari** [comment]
Try this:
curl -s -X PUT ‘{“wallSwitch: true“}’ http://127.0.0.1:46237/gateways/00212EFFFF06A0F1/accessories/7CB03EAA00AF52C0/settings

**Comment by xBilyz3** [comment]
also does not work :(

curl -s -X PUT ‘{“wallSwitch“: true}’ http://127.0.0.1:46237/gateways/00212EFFFF06A0F1/accessories/7CB03EAA00AF52C0/settings

**Comment by ebaauw** [comment]
See the WIki

**Comment by xBilyz3** [comment]
the description in the wiki leads to the error:
curl: option --json: is unknown

**Comment by xBilyz3** [comment]
> See the WIki

the description in the wiki leads to the error:
curl: option --json: is unknown

**Comment by ebaauw** [comment]
RTFM https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#example-3

**Comment by xBilyz3** [comment]
> RTFM https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#example-3

thank you have read over it. works now
