### ISSUE TITLE
Zero bridgeid

### ISSUE THREAD

**Issue by honza67** [ebaauw/homebridge-deconz#129]
Hello,
I see the following recurring warning in the log on the RPi4 with HB and the Conbee II connected to the USB cable:

_[deCONZ] warning: 00000000000000000000: not a RaspBee/ConBee mac address_

Here I can see that Conbee has a null bridge ID.

pi@homebridge:/var/lib/homebridge $ ph discover
{
  "192.168.1.45": {
    "apiversion": "1.56.0",
    "bridgeid": "001788FFFE6B688C",
    "datastoreversion": "147",
    "factorynew": false,
    "mac": "00:17:88:6b:68:8c",
    "modelid": "BSB002",
    "name": "Philips hue",
    "replacesbridgeid": null,
    "starterkitid": "",
    "swversion": "1956178040"
  },
  "192.168.1.95:4530": {
    "apiversion": "1.16.0",
    "**bridgeid": "0000000000000000**",
    "datastoreversion": "93",
    "devicename": "ConBee II",
    "factorynew": false,
    "mac": "d8:3a:dd:03:d4:68",
    "modelid": "deCONZ",
    "name": "Phoscon-GW",
    "replacesbridgeid": null,
    "starterkitid": "",
    "swversion": "2.21.1"

I haven't found any solution on the web to fix the problem. Can you please help me?
J.K.

**Comment by ebaauw** [comment]
Sorry, I cannot.  This is an issue with deCONZ, that sporadically occurs.  I don't know what causes it, nor how to solve it.  Best ask in the deCONZ support forum
