### ISSUE TITLE
Name of group Scenes will be overwritten

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-deconz#130]
Happy Easter Erik,
short info to you. The problem with the overwritten scene names in the group also exists in homebridge-deconz.

If I change the name of the scene switch in the group in Homekit, this is overwritten after a homebridge restart again with the name value that is stored in deCONZ.

If I understood you correctly in Issue https://github.com/ebaauw/homebridge-hue/issues/1150, the problem should no longer exist with homebridge-deconz?

Best regards

**Comment by ebaauw** [comment]
Sorry didn't have time to look into this yet.  Does it still go wrong with v0.1.12 (or v0.1.11)?

**Comment by Nastras** [comment]
No ding. I myself have not yet come to investigate the deCONZ/Ambilight thing further. Wanted me with the result still report to you the days 😉.


Yes, the problem is still there. However, it can be easily readjusted. Create a group with one scene. Rename the switch for the scene to HK then restart homebridge. Now the self created name is gone and the original scene name is displayed again.

I have this behavior only with the scene switches in groups.


Ps. After two days of using homebridge-deconz I have to say that the plugin really runs great. Very good work. Thank you 👌!

**Comment by ebaauw** [comment]
There's actually some leftover code from when I tried and sync the HomeKit names to the resource names and vice versa.  This actively overwrites the HomeKit name, but apparently HomeKit only picks this up, after restarting Homebridge.

There's even a bigger issue, that brightness and colour control are missing from the group main service.

**Comment by ebaauw** [comment]
In v0.1.13.

**Comment by Nastras** [comment]
Good morning Erik,

very good that you could understand the problem and have already implemented a fix 👌. I am currently not at home but have installed the update and made a few successful test remotely. I think now everything works as expected. If I notice anything else about this case when I'm back home I'll report again.

Thank you very much!
