### ISSUE TITLE
warning: using default xy gamut

### ISSUE THREAD

**Issue by JanLp** [ebaauw/homebridge-deconz#131]
homebridge-deconz v0.1.12

```
    "manufacturer": "Philips",
    "model": "LST002",
    "name": "Server",
    "resources": [
      "/lights/12"
```

**Comment by ebaauw** [comment]
The gamut should be exposed by the deCONZ API, under `capabilities`.  Make sure deCONZ exposes the light through its DDF, `devices/philips/light_zll_C.json`.

**Comment by JanLp** [comment]
I don't use the deCONZ GUI

The lightstrip is the first version `LightStrip plus (original Philips version, detachable strip, fixed power cord, smaller case, blue retail packaging)` https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions#philips-hue-signify and has the latest firmware

From REST API

```
{
    "capabilities": {
        "alerts": [
            "none",
            "select",
            "lselect"
        ],
        "color": {
            "ct": {
                "max": 500,
                "min": 153
            },
            "effects": [
                "none",
                "colorloop"
            ],
            "modes": [
                "ct",
                "effect",
                "hs",
                "xy"
            ]
        }
    },
    "colorcapabilities": 31,
    "config": {
        "groups": [
            "0"
        ]
    },
    "ctmax": 500,
    "ctmin": 153,
    "etag": "cf44627774cd1c6f7f9116441893078a",
    "hascolor": true,
    "lastannounced": "2022-10-11T09:48:10Z",
    "lastseen": "2023-04-10T07:25Z",
    "manufacturername": "Philips",
    "modelid": "LST002",
    "name": "Server",
    "state": {
        "alert": "none",
        "bri": 191,
        "colormode": "xy",
        "ct": 153,
        "effect": "none",
        "hue": 46134,
        "on": false,
        "reachable": true,
        "sat": 254,
        "xy": [
            0.1539,
            0.077
        ]
    },
    "swversion": "5.130.1.30000",
    "type": "Extended color light",
    "uniqueid": "00:17:88:01:01:21:f4:d4-0b"
}
```

**Comment by ebaauw** [comment]
> I don't use the deCONZ GUI

That's your choice...  Short of re-pairing the device, I don't think there is another way to force-read the manufacturer name.

Closing this issue, as it's really an issue with deCONZ.  I'll see if I can do some magic there, changing the DDFs so they match `"Philips"` as well, and update `manufacturername`.
