### ISSUE TITLE
Aqara Vibration Sensor

### ISSUE THREAD

**Issue by sirinveen** [ebaauw/homebridge-deconz#132]
Hi,

I can see the sensor by deCONZ but unfortunately I cannot see in Eve Apps why?

![image](https://user-images.githubusercontent.com/102876220/230953501-ceac1b0e-b47f-413e-a9cd-011c596adac0.png)

I delete the sensor and retry many time but no success to see in Eve Apps.

**Comment by ebaauw** [comment]
Check the dynamic configuration for the device.  See Wiki.
