### ISSUE TITLE
UI API does not show any gateways

### ISSUE THREAD

**Issue by KoljaV** [ebaauw/homebridge-deconz#134]
Hi,

There is a bridge shown in the UI. However the API does not show any Gateway. Is there someone who knows what I am doing wrong?

BR,
Kolja

![2A2A2466-1BA9-4452-B6FC-E1A313CCBC9C](https://user-images.githubusercontent.com/25928990/232200302-4ba20585-94c0-4dda-bb5b-e6518bcb8b3c.jpeg)
![B7E1FC70-9899-4BCB-BFB8-308FDBD9F3D2](https://user-images.githubusercontent.com/25928990/232200307-cc7b21c1-44b7-4eee-ab38-e55e332588f1.jpeg)

**Comment by ebaauw** [comment]
The screenshot shows the Homebridge child bridge, as configured by the Homebridge UI in `config.json`.  This has nothing to do the deCONZ gateway as seen by Homebridge deCONZ.

On new installations, Homebridge deCONZ won't show the gateway until either:
- It has obtained an API key and is exposing (devices connected to) the gateway.  Note that when running Homebridge on a different server than deCONZ, you need to unlock the gateway for Homebridge deCONZ to obtain an API key;
- It has given up obtaining an API key and is not exposing (any devices connected to) the gateway.  This timeout takes a couple of minutes.
Check the Homebridge log for details on what Homebridge deCONZ is doing.

**Comment by KoljaV** [comment]
Hi, thanks for the clarification!
I guess that the API key was obtained. But somehow no devices are exposed, although one zigbee switch is connected via the deconz App.

![1073BF04-0732-4608-9D7D-5C34D3AB5CE3](https://user-images.githubusercontent.com/25928990/232207501-1232d4d5-5a1c-459a-aea5-e087c4baedec.jpeg)

**Comment by ebaauw** [comment]
I guess not, or Homebridge deCONZ would have created an accessory for the gateway to persist the API key.

**Comment by KoljaV** [comment]
Thanks for your help! That is much appreciated!
Yes, you are right. There is no gateway accessory. Thus, I also cannot reinitiate the creation of the API key, right? I reinstalled the deconz plugin and this is the output: 
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/25928990/232288980-1e1b1e13-439e-4d98-aff9-35ba46e830fb.png">
There is no API Key request in the logs, right? How can I trigger the API Key Request if I have no gateway accessory.

**Comment by ebaauw** [comment]
Check the log: Homebridge deCONZ tries to obtain the API key on startup.  After a couple of minutes it gives up and exposes the gateway accessory based on the limited info it provides unauthenticated.

**Comment by KoljaV** [comment]
Ok, got it. It's up to deconz. Somehow the API gives back zeros for the bridgeID. I don't know why. So far, all of the found hints did not help me
<img width="385" alt="image" src="https://user-images.githubusercontent.com/25928990/232314803-6269b1f4-8898-4cb7-9ec9-0ce0081f8df9.png">

**Comment by ebaauw** [comment]
I've never experienced this myself, but seen several reports of this (e.g #51, #129).  I don't know what causes this, nor how to fix it. Best ask on de deCONZ support forum.

**Comment by KoljaV** [comment]
SOLVED: Resetting the GW via the GUI helped.
Thanks a lot for your support @ebaauw !
