### ISSUE TITLE
hppts status 404 not found 

### ISSUE THREAD

**Issue by rrook97** [ebaauw/homebridge-deconz#136]
hello everyone,

what do I wrong.
after installing homebridge deconz i get the message https not found while i have entered ip address and port and i think i can't do more??

**Comment by ebaauw** [comment]
Please attach the log file.

**Comment by rrook97** [comment]
<img width="1344" alt="Scherm­afbeelding 2023-04-19 om 06 45 03" src="https://user-images.githubusercontent.com/68957111/232969159-9adf1c57-7264-48f4-a868-57d43f2f8f5e.png">

this is de log of homebridge

**Comment by ebaauw** [comment]
This is an issue with your deCONZ gateway: it doesn’t expose `/groups/0`.  I’m not sure what’s causing this, nor how to fix it.  Best ask in the deCONZ support forum.
