### ISSUE TITLE
unknown ZHASwitch

### ISSUE THREAD

**Issue by ghost** [ebaauw/homebridge-deconz#137]
deCONZ v2.22.00
homebridge-deconz v0.1.13

No errors with v2.21.2

`Bad: warning: /sensors/40: unknown ZHASwitch: {"config":{"clickmode":"rocker","devicemode":"compatibility","on":true,"reachable":true},"ep":41,"etag":"e736dd8cce2f6ffabf34204e05cad7a8","lastannounced":null,"lastseen":"2023-04-21T12:56Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.switch.n0agl1","name":"Switch 40","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"54:ef:44:10:00:15:95:18-29-0012"}`

```
{
    "capabilities": {
        "alerts": [
            "none",
            "select",
            "lselect"
        ]
    },
    "config": {
        "groups": [
            "0",
            "3"
        ]
    },
    "etag": "5b44ddf4637ec5859b964873a5aaa36e",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2023-04-21T13:11Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.switch.n0agl1",
    "name": "Bad",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": true
    },
    "swversion": "0.0.0_0021",
    "type": "On/Off light",
    "uniqueid": "54:ef:44:10:00:15:95:18-01"
}
```

**Comment by ebaauw** [comment]
> deCONZ v2.22.00
> No errors with v2.21.2

Weird, I don’t see any changes for this device in v2.22.0.  Is it exposed by DDF or by legacy code?  Did you pair other devices, causing the ZHASwitch resource to be exposed?

**Comment by JanLp** [comment]
It's exposed through legacy code. The only thing I have done is to update deCONZ to version 2.22.00

`Does it even expose button events?`

Nope

**Comment by ebaauw** [comment]
I think they created a DDF for it in v2.22.0, but I don't understand what they would want with the ZHASwitch resource, as there's no button events defined.  Needs to be solved in deCONZ, before I can do anything here.
