### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by drodmantras** [ebaauw/homebridge-deconz#14]
Do you have to uninstall previously installed HomeBridge-hue plugin? My phoscon website doesn't seem to take the new plugin but shows version of homebridge-hue plugin under "homebridge version"

**Comment by drodmantras** [comment]
For now should i update both or just the deconz one?

**Comment by ebaauw** [comment]
Just update Homebridge Hue for now.

**Comment by drodmantras** [comment]
Thank you
