### ISSUE TITLE
Cannot set Color of Bulbs

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-deconz#140]
Hi Erik!

I cannot set or change  Color Values for Color bulbs within the home App. It works flawless within the Phoscon App though.
I get this error message for all color lights:

`13.5.2023, 15:29:49] [deCONZ] RaspBee Gateway: warning: request 1943: /lights/1/state/xy: api error 7: invalid value, , for parameter, xy`

Do you have an idea to fix it ?

thx,
Paul

**Comment by ebaauw** [comment]
Please attach the dump file, set `logLevel` for the light to 2, and capture a log file, while changing the light colour.

**Comment by beatpaul** [comment]
Cannt do it anymore,
After playing around and trying to fix it myself by updating my pi
The color lights moved to standard room and the adaptive light advice appeard in home app
Everything works now egain
Sorry for bothering u, maybe u can get something out of it for your great plugin:)
