### ISSUE TITLE
Buttons are pressend when Status is faulty

### ISSUE THREAD

**Issue by KoljaV** [ebaauw/homebridge-deconz#141]
Hi,

I have the following issue. I restart my RPI every night at 03:00 so all of the services are restarting. Sometimes, it then happens that all my zigbee switches are behaving like some would have pressed the button. This is obviously not the case because everyone is sleeping. ;) I guess my switches are in a faulty (not connected) state in the GW because my zigbee range extender (made by IKEA) need some time to reinitiate its connection to the ConBee Stick. In addition, I found the lines in the log: 
![image](https://github.com/ebaauw/homebridge-deconz/assets/25928990/29c06555-82a3-45e9-96bf-9c5d4bbb7b80)
Is is possible to change that behavior somehow?

BR,
Kolja

**Comment by ebaauw** [comment]
The log message has nothing to do with a button press.

Are you on v1.1.15 or on an earlier version?  v1.1.15 fixes a bug related to ghost button actions on restart, see #139.

**Comment by KoljaV** [comment]
Thanks for the info! I updated to 1.1.15.
