### ISSUE TITLE
    "noResponse": true setting is not working

### ISSUE THREAD

**Issue by patmuk** [ebaauw/homebridge-deconz#143]
Hi,

besides missing from the UI ("Advanced settings") it is not working when added to the json file.
Lights still are shown as "on" or "off" instead no response in HomeKit, Homebridge log says the device is not reachable (correct) and thus the status cannot be changed.

**Comment by ebaauw** [comment]
Because it hasn’t been implemented.  See also https://github.com/ebaauw/homebridge-deconz/issues/38.

**Comment by patmuk** [comment]
Ah, that explains ;) Maybe you can add this info to the configuration page at https://github.com/ebaauw/homebridge-deconz/wiki/Configuration (like a foodnote, referring to this issue).
Thanks!
