### ISSUE TITLE
Log flooded with - Programmable Switch Event: Single Press

### ISSUE THREAD

**Issue by Domser21** [ebaauw/homebridge-deconz#145]
Phoscon-GW Button: Programmable Switch Event: Single Press
Showing this events is not helpful - is there not a way to filter these events in the plugin? They are of no use- searching different forums, many have the problem.

I have seen quite a few comments about this here, your answer is always the Wiki - which is fine for people who understand the lingo.

But please - for us people without the knowledge - could you write a short guide what exactly one should change in Homebridge to make the flooding of the log stop - by this device? As quite a few people out there, I do not even know what it ist and why I need it...

Please explain as you would to a 3 year old. Where should I change something and what exactly?

Thanks so much!

Also thanks for your great plugin,

**Comment by MSL-DA** [comment]
It's described quite nicely, so do yourself a favor and read: https://github.com/ebaauw/homebridge-deconz/wiki/Configuration

And also read this post: https://github.com/ebaauw/homebridge-deconz/issues/30#issuecomment-1077885988

**Comment by Domser21** [comment]
@MSL-DA thanks, as I have written - I have read the comment and the linked wiki article - but I do not understand it.

yes, I am that ignorant. But I am also not the only one.

It would be wonderful if you could help. Reading all the closed threads and the wiki have sadly not helped me.

**Comment by MSL-DA** [comment]
> I do not even know what it ist and why I need it...

https://github.com/ebaauw/homebridge-deconz/issues/30#issuecomment-1077885988 _It's to enable periodic automations._

> But please - for us people without the knowledge - could you write a short guide what exactly one should change in Homebridge to make the flooding of the log stop - by this device?

https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#update-accessory-settings

**Comment by MSL-DA** [comment]
I'll admit it's not straightforward, but remember that Homebridge deCONZ is under development and I'm sure Erik's goal is to make it more user-friendly/PnP

**Comment by Domser21** [comment]
@MSL-DA just giving me the instructions that I simply do not understand again, does not help me.
Yes I have read the Wiki and no - I do not understand it.
Could just aswell be in klingon.

Help would be:
Open…
Put in…
etc

Just pretend you are writing to a rather simple 3 year old

**Comment by MSL-DA** [comment]
It's under the Wiki... if you've read it and don't understand it, it won't help you if I copypaste those instructions. I have linked to specific help topics that tell you what to do.

By the way, I can't write to a 3-year-old, because I don't expect him to understand ;)

I guess I have nothing more to contribute. Hope you figure it out.

**Comment by Domser21** [comment]
@MSL-DA  you should become a teacher, you are great at explaining ;-)). Joke aside, I guess you cannot imagine why the wiki was not helpful. Which is fine. We are on a different experience level.

for starters where would I change stuff?!? Obviously not in the config. Using the console?

thanks for trying to help

**Comment by Domser21** [comment]
A very kind soul on a forum created a step-by-step guide for me and I could easily follow it and fix my problem.

Yes the info is in the wiki - but it is swamped with so much info, that it is overwhelming for a beginner.
Now having gone through the process, I understand the wiki  - but before, I could not make any sense of it.

Maybe a condensed version of what one should do on the Wiki would help simple users like myself?!?

It is actually all pretty easy, once you know what to do. 

The big problem is, once you have all the knowledge, it is hard to imagine what it was like before one knew how to do stuff.
There may be parts that seem completely obvious - but to a beginner they are not.

all in all, I am happy - my logs are not flooded anymore.

**Comment by MSL-DA** [comment]
To find your bridgeid look for this in you log

![Skærmbillede 2023-05-30 kl  12 25 39](https://github.com/ebaauw/homebridge-deconz/assets/134940586/1ce329f8-ac26-4605-826e-343d84c1555c)

open terminal in homebridge ui

type curl -s http://xxx.x.x.x:xxxxx/gateways | jq

look for bridgeid

type curl -s -X PUT -d '{"logLevel": 0}' http://xxx.x.x.x:xxxxx/gateways/bridgeid/settings | jq

**Comment by MSL-DA** [comment]
If it is too difficult, then I would recommend that you use: https://github.com/ebaauw/homebridge-hue until Erik is "finished" with Homebridge deCONZ

**Comment by Domser21** [comment]
as I wrote before, it is actually very easy, given precise instructions. It is only 3 steps. The trouble with the Wiki is, it gives all possible info and instructions - which is great - but can be confusing.

Once I knew exactly what to do, it took me about a minute - very easy. (Look at my post above)

But in general, I still do not understand the point of Phoscon-GW Button: Programmable Switch Event: Single Press
flooding the log - it was never in the home bridge-hue plugin and I am not sure anyone missed it.

**Comment by MSL-DA** [comment]
Again ... Homebridge deCONZ is under development. Not very user friendly, but if you read https://github.com/ebaauw/homebridge-deconz#work-in-progress you would have known this too.

Erik's Wiki is quite useful, maybe not for a 3 year old ... but I don't think it's relevant for someone that age ;) I'm pretty sure this section will become irrelevant as soon as he finishes the implementation.

> But in general, I still do not understand the point of Phoscon-GW Button: Programmable Switch Event: Single Press
flooding the log - it was never in the home bridge-hue plugin and I am not sure anyone missed it.

It's because you don't want to read the answers you get. I have answered you twice on that question, and also linked to an answer.  https://github.com/ebaauw/homebridge-deconz/issues/30#issuecomment-1077885988

But now that you've solved your problem, you can close the thread so we don't have to spend more time on it ;)

**Comment by Domser21** [comment]
The statement that a short 3step guide in the wiki would help, is valid.

MSL-DA your posts have actually not been helpful at all, neither to a 3 year old - nor to a 60 year old. So thanks for being so overbearing. 
yes, you know your way around here better than I - I hope this made your day. Thanks

**Comment by MSL-DA** [comment]
The statement that a short 3 step guide in the wiki would help is valid.

No, it's not. You're lazy, that's what you are.

But now that you've gotten help, maybe you could write your solution so that "everyone" else doesn't have to ask the same question?

**Comment by martind1983** [comment]
I was facing same issues as Domser21, this way of doing the config was new to me, nevertheless, I learned it, not with the answers here, but from the smartapfel forum.

The really really great description can be found here: https://forum.smartapfel.de/forum/thread/9763-homebridge-deconz-in-entwicklung-beta/?postID=143589#post143589

**Comment by ellzzett** [comment]
Is there any special command I have to use to have this change of logleve in permanent memory? Because when the RapsberryPi restarts the change of the loglevel is back to 2. Thx in advance!

**Comment by ebaauw** [comment]
The log level is persisted in `cachedAccessories`.  If it resets after rebooting the Raspberry Pi, there's something wrong with your setup.  Most likely a corrupted uSD card, that has turned read-only.
