### ISSUE TITLE
Vibration sensor aqara does not keep value

### ISSUE THREAD

**Issue by Nastras** [ebaauw/homebridge-deconz#148]
Hi Erik, I have a small problem with a vibration sensor from Aqara. When I use Sensitive, Duration or Enable the new vale jumps back to the original value after a short time. It does not save the new values.
For all other aqara devices, it saves the adjusted new values.

Should the behavior with homebridge-deconz not be past or is it a bug?

**Comment by ebaauw** [comment]
Setting _Enabled_ updates _Status Active_, but doesn't update `config.on` on the deCONZ gateway.  This is a bug (simply missing the code needed for this) alright.  Not just for the `lumi.vibration.aq1`, but for any (service based on a) `sensors` resource.

Setting _Duration_ or _Motion Sensitivity_ from Eve should work.  Note however:
- Eve only supports some pre-defined values for _Duration_.  Homebridge deCONZ will report _Duration_ as the nearest value to `config/duration` (or `config/delay`), so a value of 65 (seconds) is reported as 2 min).  When setting _Duration_ to the lowest value (5 secs), Homebridge deCONZ sets `config/duration`(or `config/delay`) to 0.
- For DDF-exposed devices, you need the changes from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6919 to have the API plugin reset automatically `state/vibration` (or `state/presence`) after `config/duration` seconds.  The PR is included from v2.22.1-beta onwards
- Homebridge deCONZ assumes the API deCONZ normalises the values for `config/sensitivity` from `0` (lowest) to `config/sensitivitymax`.  For the `lumi.vibraton.aq1`, this is only done by the DDF from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6919, which is included from v2.22.1-beta onwards.
- While `config/duration` is handled purely by deCONZ, `config/sensitivity` and `config/delay` need to be written to the Zigbee device.  This might be challenging for sleepy devices, like the `lumi.vibration.aq1`, especially when exposed through legacy code.

**Comment by Nastras** [comment]
Thanks for the great explanation 👌

I am not familiar with the DDF thing so far. I wanted to have a look at it for some time but have not yet got around to it. Therefore, I have all devices standard integrated without changes. Is it worth to get familiar with the DDF function?

If I understood you correctly you can fix the behavior but with a fix in an update or?

**Comment by ebaauw** [comment]
DDF is just the new way of how deCONZ adds support for (new) devices.  Each new version includes more and more DDFs, and deletes the legacy code bit by bit.  Unless you want to add support for new devices, you don’t need to handle DDFs yourself.

`config/on` will be fixed in the next release of Homebridge deCONZ.  For the others you need deCONZ v2.22.1-beta, or a subsequent stable release.

**Comment by ebaauw** [comment]
> `config/on` will be fixed in the next release of Homebridge deCONZ.

v0.1.19.
