### ISSUE TITLE
Scan for devices

### ISSUE THREAD

**Issue by MSL-DA** [ebaauw/homebridge-deconz#149]
Why is homebridge deconz scanning for devices in the background. I don't want that! In Phoscon I have "activate discovery" to off

**Comment by ebaauw** [comment]
Because you configured it to do so.  If you don't want that, set `hosts` to disable automated discovery of gateways.

**Comment by MSL-DA** [comment]
That's not what I meant. I meant devices such as lights etc.
It's annoying that devices are added in the background.
But it occurs to me that in reality it is not related to Homebridge deCONZ
