### ISSUE TITLE
OTAU

### ISSUE THREAD

**Issue by MSL-DA** [ebaauw/homebridge-deconz#152]
Why are all files from https://github.com/Koenkk/zigbee-OTA stored in `/var/lib/homebridge`?

And are all files supposed to be downloaded from index.json regardless of whether the device exists in my setup?

**Comment by ebaauw** [comment]
They're downloaded into the current directory.  You might want to login as the user running deCONZ and change to `~/otau` (which is where the deCONZ OTAU plugin will be looking).

Right now all files are downloaded.  I plan to add command-line parameters in a later stage. to download a single image, or images from a single vendor.

**Comment by MSL-DA** [comment]
> They're downloaded into the current directory. You might want to login as the user running deCONZ and change to `~/otau` (which is where the deCONZ OTAU plugin will be looking).
> 
> Right now all files are downloaded. I plan to add command-line parameters in a later stage. to download a single image, or images from a single vendor.

Thanks for the answer 👍
