### ISSUE TITLE
Getting API key fails

### ISSUE THREAD

**Issue by JanMisker** [ebaauw/homebridge-deconz#153]
The homebridge logs tell me to `unlock gateway and set Expose to obtain an API key`. However I don't see the `Expose` attribute in Eve anywhere? I only see a `Search` attribute that I can switch to 'off' or 'on', and I do see a log of that in homebridge logs, but immediately after that I get api auth error.
```
[7/24/2023, 12:19:08 PM]  [deCONZ] CJ Gateway: Search: changed to true (from false)
[7/24/2023, 12:19:08 PM] [deCONZ] CJ: request 3: PUT /config {"permitjoin":120}
[7/24/2023, 12:19:08 PM] [deCONZ] CJ: warning: request 3: /: api error 1: unauthorized user
[7/24/2023, 12:19:08 PM] [deCONZ] CJ: warning: /: api error 1: unauthorized user
```
(The gateway is named CJ).

I can get api key on command line: 
```
$ deconz getApiKey
"XXXX"
```

Anything else I can try?

I'm on `homebridge-deconz@0.1.20` and all dependencies are also updated.

**Comment by ebaauw** [comment]
These dynamic configuration settings are no longer exposed to HomeKit, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.

Issue `ui put / "{"expose": true}` to set expose.

**Comment by JanMisker** [comment]
Got it, thanks. 
It's one of those things that just continues running very stable in my home, but sometimes there's a change needed and then I find out about all the changes 😃

Thanks for your work!
