### ISSUE TITLE
how to expose sensors and switches separately

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#16]
hey,

is it possible to expose only "sensors" OR "switches"?

i need a 2nd bridge with homebridge-deconz which **only** expose real sensors (eg. temp,  contact, motion, smoke).

thank you!

**Comment by ebaauw** [comment]
Yes, set _Expose Sensors_ and then unselect _Expose_ on each sensor, or switch.  The blacklist is now per Homebridge deCONZ instance, no longer per deCONZ gateway (as is was with the resource links in Homebridge Hue).
