### ISSUE TITLE
"Valve" not (yet?) supported

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-deconz#160]
I want to migrate my homebridge-hue to homebridge-deconz. I had a `valve` resource link in homebridge-hue but I cant find that option in homebridge-deconz. wallswtich and venetianBlind are now in dynamic configutation but not "valve". Is is unsupported? Will it be supported?

**Comment by ebaauw** [comment]
The setting would be `ui put /accessories/`_mac_` '{"serviceName": "Valve"}'` (or `"Light"`, `"Outlet"`, or `"Switch"`), but `"Valve"` has yet to be implemented.  See https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#settings-2.

**Comment by ebaauw** [comment]
In v1.0.1.
