### ISSUE TITLE
TRADFRI SHORTCUT Button Button: No Dubbel press in Homekit

### ISSUE THREAD

**Issue by frogger11** [ebaauw/homebridge-deconz#163]
Hi, 
I've switched over to the new Deconz plugin, but I've noticed that double-clicking doesn't seem to work with Homekit. I've updated to the latest firmware version on my Conbee2 and the latest Docker version of Deconz. Please see the logs below.

-----
Homebridge log:
[deCONZ] TRADFRI SHORTCUT Button Button: Programmable Switch Event: Single Press
[deCONZ] TRADFRI SHORTCUT Button Button: Programmable Switch Event: Long Press

Docker: DeConz community:Latest:
Button 1001 - TRADFRI SHORTCUT Button, unicast to: 0x0000, endpoint: 0x01, cluster: LEVEL_CONTROL (0x0008), action: Move up (with o
n/off), payload: 0053, zclSeq: 22                                                                                                                        
13:32:53:906 [INFO] - Button 1003 - TRADFRI SHORTCUT Button, unicast to: 0x0000, endpoint: 0x01, cluster: LEVEL_CONTROL (0x0008), action: Stop (with on/o
ff), payload: None, zclSeq: 23                                                                                                                           
13:33:01:922 [INFO] - Button 1002 - TRADFRI SHORTCUT Button, unicast to: 0x0000, endpoint: 0x01, cluster: ONOFF (0x0006), action: On, payload: None, zclS
eq: 24                                                                                                                                                   
13:33:08:152 [INFO] - Button 2004

These plugins have done an excellent job, without them, my smart home would have been very different, and not for the better :).
Thank you!

**Comment by ebaauw** [comment]
This is a bug in deCONZ: it sends a 2004 instead of a 1004 on double press.

**Comment by ebaauw** [comment]
As far as I can tell this bug has been there, since support for double press was added.  Apparently, Homebridge Hue was a bit more forgiving, unintentionally.

Fix should be in next deCONZ beta.  As workaround, you can manually edit `button_maps.json`.
