### ISSUE TITLE
Configurable WebSocket port

### ISSUE THREAD

**Issue by jnssnmrcs** [ebaauw/homebridge-deconz#164]
Would be great if you could add support for setting a web socket port other than the default 443. I'm running deconz in a docker image and is binding it to a different port.

**Comment by ebaauw** [comment]
No it wouldn't.  The websocket port is actaully reported by the deCONZ API - no need to configure it manually.

**Comment by jnssnmrcs** [comment]
hm my bad, I missed the env vars to control which port deconz uses for websocket, having some issues getting it to work though, but that's outside the scope of this plugin. Thanks, closing.
