### ISSUE TITLE
Temperature Sensors no longer display properly in the Eve App

### ISSUE THREAD

**Issue by karQs** [ebaauw/homebridge-deconz#165]
I have two sonoff temp/humidity sensors and after updating the Eve app to 6.1.4 I can no longer view the sensor in the eve app in the "at a glance" view or by selecting the room. Oddly I can still view the sensors normally if I navigate to "types" under the room tab and then click humidity.

**Comment by jan666** [comment]
I have a few SONOFF SNZB-02 (T/H) and they don't show in eve's room view / at a glance

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/42955b90-0464-42f6-b69d-c4624789ad65)

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/6dcdc1f4-26c0-4768-8815-e10c41d6122c)

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/dfdb13e4-b030-4712-a3b2-44af70304708)

**Comment by ebaauw** [comment]
> I have a few SONOFF SNZB-02 (T/H) and they don't show in eve's room view

That's the first screenshot, I take it?

The second screenshot is the type view?  I've never seen that icon before (the thermometer between <> brackets).

The third screenshot (from Home?) suggests it's exposed OK, as far as I can tell here.

Did you un-expose/re-expose the accessory after upgrading Eve?  Note: not suggesting you should do this - just trying to understand what's changed.

Could you please attach the debug dump file, or at least list the resources deCONZ uses to expose the sensor?  Also, could you set the `logLevel` of this accessory to 2 (using the `ui` command) and restart Homebridge deCONZ, while capturing the logfile and attach it?

**Comment by ebaauw** [comment]
Just updated Eve to 6.1.4 on my iPad.  The DHT sensor still looks alright, just the same as under 6.1.3.  Are you running iOS/iPadOS 16.6.1?

**Comment by jan666** [comment]
The first screenshot it the room view in Eve (Sensor is missing), the second is the "type" view in Eve.

I am on the latest Eve version on an iPad with latest iPadOS 16. 

Sensors with Pressure (like Aqara) show up (like you said) without problem.

It might just be a problem in the Eve app...?

```
{
  "id": "00124B0022150020",
  "manufacturer": "eWeLink",
  "model": "TH01",
  "name": "Sensor DG Erik",
  "resources": [
    "/sensors/40",
    "/sensors/41"
  ],
  "settings": {
    "expose": true,
    "logLevel": 2,
    "lowBatteryThreshold": 20
  },
  "type": "sensors",
  "zigbee": true
}
```
```
{
  "config": {
    "battery": 72,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "34f5510367a78ec6e5c7ce737496d8d3",
  "lastannounced": "2023-09-10T21:30:10Z",
  "lastseen": "2023-09-15T05:11Z",
  "manufacturername": "eWeLink",
  "modelid": "TH01",
  "name": "Sensor DG Erik",
  "state": {
    "lastupdated": "2023-09-15T05:10:04.007",
    "temperature": 2230
  },
  "swversion": "20200718",
  "type": "ZHATemperature",
  "uniqueid": "00:12:4b:00:22:15:00:20-01-0402"
}
```

```
{
  "config": {
    "battery": 72,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "400c28b64ac9d017c270b236efa9da68",
  "lastannounced": "2023-09-10T21:30:10Z",
  "lastseen": "2023-09-15T05:11Z",
  "manufacturername": "eWeLink",
  "modelid": "TH01",
  "name": "Sensor DG Erik",
  "state": {
    "humidity": 6676,
    "lastupdated": "2023-09-15T05:11:42.754"
  },
  "swversion": "20200718",
  "type": "ZHAHumidity",
  "uniqueid": "00:12:4b:00:22:15:00:20-01-0405"
}
```

**Comment by ebaauw** [comment]
It's definitely something in the Eve app.  Not sure I can figure out what's triggering this, and whether I could prevent it in Homebridge deCONZ.  The resources and settings look normal, regular, and shouldn't cause any weirdness.

Kinda like the nuclear option, but would you be able to try:
- Un-expose the sensor; wait a couple of minutes for HomeKit to sync the changed configuration to all devices; re-expose the sensor;
- Try Eve on a different device; or un-install the Eve app; re-install the Eve app.

**Comment by jan666** [comment]
un-exposed for 30 minutes. Installed Eve on an iPhone where it was never installed before. No changes.

**Comment by ebaauw** [comment]
Very weird.  I would need to double-check how the device is exposed to HomeKit.  Maybe setting `logLevel` to 2 and capturing the log while Homebridge is starting would reveal something, but ideally I would use HMCatalog and or HomeSpy to examine the accessory.  I'm sorry, but I wouldn't know how to do that remotely.

**Comment by jan666** [comment]
I installed HomeSpy but it just crashes all the time.

I set logLevel to 4 (the result showed 3) and captured the output of homebridge -D. Can I send it to you without posting it in the public?

**Comment by ebaauw** [comment]
Sure, PM me on Discord.

**Comment by ebaauw** [comment]
The logfile looks all good to me.  As far as I can tell, the sensor is exposed to HomeKit the same as my DHT sensor by Homebridge RPi, except that that doesn't expose any battery.

I created a couple of CLIP sensors to mimic your eWeLink:
```
{
  "config": {
    "battery": 72,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "etag": "2920bcd72a63615bc0b686b5e0a14559",
  "manufacturername": "eWeLink",
  "modelid": "TH01",
  "name": "Test",
  "state": {
    "lastupdated": "2023-09-18T20:45:21.536",
    "temperature": 2230
  },
  "swversion": "20200718",
  "type": "CLIPTemperature",
  "uniqueid": "00:12:4b:00:22:15:00:20-01-0402"
}
```
```
{
  "config": {
    "battery": 72,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "etag": "bd2f4d197ad6087863f4fb9710151d5b",
  "manufacturername": "eWeLink",
  "modelid": "TH01",
  "name": "Test",
  "state": {
    "humidity": 6676,
    "lastupdated": "2023-09-18T20:45:38.155"
  },
  "swversion": "20200718",
  "type": "CLIPHumidity",
  "uniqueid": "00:12:4b:00:22:15:00:20-01-0405"
}
```
And, damn, after exposing it to HomeKit, I see the same as you in Eve.  If you check under _Accessories_, you'll find Eve thinks it's an [Eve Thermo Control](https://www.evehome.com/en/eve-thermo-control).  I think Eve is missing some service(s) and/or characteristic(s) from that device, and therefore not showing it in the _Room_ or _At a Glance_ views.

Ideally I would be able to mimic the Eve Thermo Control, but that won't ship until November.  And I doubt it will ship as a native HomeKit device, since they're moving to Matter so I might not (yet) have the proper tools to reverse engineer it.  For now I'll probably need to add a dummy _Air Pressure_ sensor, so Eve will think it's an Eve Room instead (and expose it like your Aqara `lumi.weather` sensors).

**Comment by ebaauw** [comment]
In v1.0.1.
