### ISSUE TITLE
Scenes created in Phoscon is not showing in HomeKit

### ISSUE THREAD

**Issue by mastrup** [ebaauw/homebridge-deconz#166]
I have created a scene in a group in Phoscon. I was expecting it to show in Homekit as an additional Lightbulb service after reading about the [run-time settings per accessory](https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#settings-2).

I have tried getting some information about my accessory by running this command:
`curl -s http://127.0.0.1:35549/gateways/00212EFFFF05565A/accessories/804B50FFFE2016CC`

It gives me this response:
```json
{
  "id": "804B50FFFE2016CC",
  "manufacturer": "IKEA of Sweden",
  "model": "TRADFRI bulb E14 WS 470lm",
  "name": "Lamp",
  "resources": [
    "/lights/5"
  ],
  "settings": {
    "expose": true,
    "logLevel": 0,
    "serviceName": "Light",
    "wallSwitch": false
  },
  "type": "lights",
  "zigbee": true
}
```

Since `exposeScenes` isn't set, I would expect it to use the default value which defaults to `true`.

I have also tried to run:
```
curl -s -X PUT --json '{"exposeScenes": true}' http://127.0.0.1:35549/gateways/00212EFFFF05565A/accessories/804B50FFFE2016CC/settings
```
but I get the following error:
```
curl: option --json: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

Am I misunderstanding how scenes is being (or should be) exposed or am I hitting a bug here?

**Comment by ebaauw** [comment]
Scenes are exposed on group accessories, not on lights accessories.
