### ISSUE TITLE
Update names w/o re-exposing

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-deconz#168]
I recently added a few new sensors. Right after adding them in Phoscon I renamed them there. But in HomeKit they just kept the old names (TemperatureXX, HumidityXX) - `ui get` had the new names. The only way I found to update the name was to unexpose und re-expose them. Is it possible to do this without re-exposing (or doing it manually)?

**Comment by ebaauw** [comment]
Names of accessories and services are handled by HomeKit, and can be changed through HomeKit apps.  The accessory itself (i.c. Homebridge) has no access to these.  Only when accessory is newly exposed to HomeKit, the names as reported by the accessory are copied.

**Comment by jan666** [comment]
Ah ok. So I guess its better to set autoExpose to false and expose new devices when they have the correct name. Thanks!

**Comment by ebaauw** [comment]
Maybe you're right.  Unfortunately, I removed the auto-expose settings and now auto-expose new Zigbee devices.  Too many people cannot read and were complaining that they didn't see any accessories.

I think it does make sense to (re-)introduce a setting to auto-expose (new) Zigbee devices, also when using multiple Homebridge deCONZ instances for the same deCONZ gateway, to overcome the 149 accessories per HomeKit bridge limit (see Discord).

**Comment by ebaauw** [comment]
In v1.0.1.
