### ISSUE TITLE
v1.0.1 > TREDANSEN block-out cellul blind

### ISSUE THREAD

**Issue by MSL-DA** [ebaauw/homebridge-deconz#170]
With version 1.0.1 TREDANSEN block-out cellul blind does not respond.

`ZigbeeGW: warning: request 267: http status 404 Not Found`

I can see the curtain in Phoscon and operate them through there.

The status of the curtain is updated in HomeKit when operated via Phoscon. But cannot be operated via the HomeKit app

`homebridge-deconz v1.0.1, node v18.18.0, homebridge v1.6.1, homebridge-lib v6.5.1`

**Comment by ebaauw** [comment]
I just found out that v1.0.1 breaks controlling _Window Covering_ and _Warning Device_ accessories.
Will issue a new version later today.

**Comment by MSL-DA** [comment]
Thanks for the reply and for your work.

**Comment by MSL-DA** [comment]
Fixed with version 1.0.2
