### ISSUE TITLE
How can I delete a single device or reload device name

### ISSUE THREAD

**Issue by royakaacky** [ebaauw/homebridge-deconz#177]
When a name of a device changes in deconz, I want to re-read this device information in homebridge. Is it possible to delete this device in the plugin so it will be reload the device by the plugin? Or can I run a command through the plugin's API to start realoding the device information ? My Idea is, that the new device name will be synced to homebridge if i want this.  But I don't want to reset the device in deconz.

**Comment by ebaauw** [comment]
HomeKit keeps its own accessory and service names, inaccessible to the accessory (i.c. Homebridge and the Homebridge plugin).  They're initialised from the values provided by the accessory on initial pairing, but live a life of their own afterwards.  The only way to "sync" them is to un-expose and re-expose the device.

**Comment by royakaacky** [comment]
How i can un-expose and re-expose it? I read the dynamic configuration documentation. But i don’t understand how i can un-expose and re-expose a accessory. Can you explain it shortly please?

**Comment by ebaauw** [comment]
See example under https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#update-device-settings to expose a devivce.  Un-exposing is similar, but using `{"expose": false}`.
