### ISSUE TITLE
Node 20 Dependencies Concern with Homebridge

### ISSUE THREAD

**Issue by TinyMito** [ebaauw/homebridge-deconz#179]
I do apologize in advance if I misunderstood the situation. I'm on Pi4 with Rasp OS Lite 64bit, apt installed the homebridge.

Current newest release **Blocks update-node from updating to version 20 on versions of Linux that don't support it.**
https://github.com/homebridge/homebridge-config-ui-x/releases/tag/4.51.1

Anything to concern about this deCONZ plugin is now requiring node ^20?

There is an open issue with people getting stuck with node ^20: https://github.com/homebridge/homebridge/issues/3453 and it seems like related to node 20 above. A few revert the node back to 18 work around.

**Comment by ebaauw** [comment]
> deCONZ plugin is now requiring node ^20?

It’s not.  https://github.com/ebaauw/homebridge-deconz/blob/ac70edbb7ad4a26c86de18a12a902ceeb97295db/package.json#L27

Note that I develop and test my plugins against the latest LTS release of NodeJS.  I issue a warning on startup when you’re using another version; the plugin might or might not run on this other version; I simply don’t have the time to test this.
