### ISSUE TITLE
Aqara Aqara Door and Window Sensor MCCGQ11LM no temperature available

### ISSUE THREAD

**Issue by SMarco360** [ebaauw/homebridge-deconz#185]
In your deconz-rest-plugin you pulled unter #6919 (Refactor Xiaomi special attribute handling in DDF) the issue of missing temperature for the Xiaomi Aqara and published in June (in 2.22.1 beta) .
[https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6919](url)

In the homebridge-deconz plugin I didn't see the update and I'm missing the data, even if provided by phoscon (see below)

`{
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 2300
    },
    "ep": 1,
    "etag": "c16176bc9b7493eca53cf83a81613f9a",
    "lastannounced": null,
    "lastseen": "2023-11-04T12:32Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.sensor_magnet.aq2",
    "name": "Balkon Zoe",
    "state": {
        "lastupdated": "2023-11-04T12:32:20.633",
        "open": false
    },
    "swversion": "0.0.0_0003",
    "type": "ZHAOpenClose",
    "uniqueid": "00:15:8d:00:08:93:8c:14-01-0006"
}`

Will this be added & data exposed in homebridge as well? - Thx

**Comment by ebaauw** [comment]
I’m sorry, I don’t understand what you’re asking
- Afaik, the referenced PR didn’t add any missing temperature; it just made sure that both the regular attribute and the special attribute are used to update the resource item for devices exposed through DDFs. I don’t see a linked issue about missing temperature;
- Homebridge deCONZ doesn’t interact with Phoscon, see deCONZ for Dummies.
- Most Xiaomi devices report their internal device temperature, which deCONZ exposes as `config.temperature`.  Homebridge deCONZ and Homebridge Hue ignore this, see https://github.com/ebaauw/homebridge-hue/issues/657.

**Comment by SMarco360** [comment]
Y Erik,
Sry. Yes the device has an internal temperature, which is exposed by deCONZ (Rest API - not Phoscon. I added the data from phoscon at its shows the data from rest API).

Didn’t know the topic was already addressed ( and closed ) in the homebridge-hue plugin. 

So: thanks for clarifying.

**Comment by SMarco360** [comment]
Closed as already explained.
