### ISSUE TITLE
Mueller Licht bulbs not showing the color red

### ISSUE THREAD

**Issue by UBEXHH** [ebaauw/homebridge-deconz#187]
The migration from hue to deconz was very successfull, thank you for the good work!
All bulbs that are connected to Phoscon/Deconz are working (Lidl, Ikea, Müller, etc.)
However only Mueller bulbs (all different models) are not able to show the color red. When I set red in HomeKit they display purple.
Those lamps also have build in effect, that the hue plugin exposed.
All other lamps from IKEA, Lidl etc. behave as they should.

**Comment by ebaauw** [comment]
Sounds like these lights aren't yet exposed properly through a DDF in deCONZ.  You should see warning messages in the Homebridge log, that Homebridge deCONZ is using the default colour gamut.

I only have one Mueller Light (a GU10 spot), but I think most of them will behave the same.  You might want to try and add the `modelid` of your bulbs to that DDF, https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/mli/zbt-extendedcolor.json.

**Comment by UBEXHH** [comment]
I migrated today from your HUE plugin to DECONZ with the help of the app "Controller für HomeKit" (Backup/Restore functionality, 7-days trial). The Müller bulbs were all functioning correctly with HUE, so I think they are exposed properly. I do not know, how to add modelids to the DDF. I have to research.

**Comment by ebaauw** [comment]
Yes, by design.  Homebridge Hue whitelists the Mueller lights, where Homebridge deCONZ relies on deCONZ exposing the light capabilities.

**Comment by UBEXHH** [comment]
I think in this case, I am rolling back to the old plugin and deactivate homebridge-deconz. I‘d have to replace all of my working Mueller bulbs and I don‘t want to. Thank you

**Comment by ebaauw** [comment]
You don’t have to replace anything.  You just need deCONZ to expose the Mueller lights through a DDF.

**Comment by UBEXHH** [comment]
Hence I did not know all the data for the bulbs for a proper DDF, I went to the nearest IKEA yesterday and bought 8 new trådfri bulbs. Too much of a hassle for me. This issue can be closed. There are too few people with Mueller tint bulbs that want all colors. Thank you for your help and answers. Best regards from Hamburg
