### ISSUE TITLE
Device Names not populated

### ISSUE THREAD

**Issue by mhin76** [ebaauw/homebridge-deconz#193]
I am using Homebrdige deCONZ v1.0.7 I noticed already on earlier version that when I pair a new device (sensor, light, ...) Phoscon App first sets a generic name, like Temperature101. After renaming it in Phoscon I still see the old name in Homebridge. Even after rebooting.
I then manually change the name on my iOS to reflect the correct device.
But now I see that in the log file of Homebridge it shows an old name (not the generic name), but I renamed it in Phoscon. Am I missing something or is this a bug?
In Phoscon my new device is called "Sicherung", on API the same:
![image](https://github.com/ebaauw/homebridge-deconz/assets/49210075/3509f881-8614-4bfc-abd3-2bf4ae4a80a4)

but on homebridge log it still shows under old name:
![image](https://github.com/ebaauw/homebridge-deconz/assets/49210075/83689041-78c8-47de-ad72-b3268044a0c7)

**Comment by jan666** [comment]
See https://github.com/ebaauw/homebridge-deconz/issues/168#issuecomment-1730926062

**Comment by mhin76** [comment]
@ebaauw wow you are fast :-) thanks for the link to the comment [#168 (comment)](https://github.com/ebaauw/homebridge-deconz/issues/168#issuecomment-1730926062) I guess we were spoiled by your previous solution where the names got updated nicely. But no worries, will make sure I track the naming translation somewhere :)
