### ISSUE TITLE
ZHAThermostat - schedules possible?

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-deconz#198]
I guess no but who knows: Is it possible to read/set the `schedule`s of `ZHAThermostat`s in the Eve App? It does not work yet - but maybe it's technically possible and maybe even planned to do? I just found out it works via deCONZ REST-API but don't know about the Eve-part.

**Comment by ebaauw** [comment]
I do think it’s technically possible, but it’s a bit tricky, and I lack the motivation to work on it.  Also, I don’t have any device to test this

I aspired to get this to work back in the day for the eCozy, but couldn’t get that TRV to work reliably.  So I abandoned that after implementing the schedules in the REST API plugin.  Although less troublesome than the eCozy, I couldn’t get the Eurotronic Spirit to work reliably either (and it doesn’t support on-device schedules), so I switched to the Eve Thermo, which uses Thread.
