### ISSUE TITLE
[deCONZ] : warning: using default xy gamut

### ISSUE THREAD

**Issue by BEskandari** [ebaauw/homebridge-deconz#199]
Hi Eric,

my best wishes for 2024. I had the below warning on my Deconz-Homebridge:
**homebridge-deconz v1.0.9, node v20.10.0, homebridge v1.7.0, homebridge-lib v6.7.3**

I have 3 Hue Play lights with the latest firmware and I get the below messages (as I intend to replace the Hue bridge with Heombridge Deconz):
_[deCONZ] : warning: using default xy gamut_

I checked and I saw that there was similar issues reported on Homebridge Hue few years ago but did not find the solution.
Is there anything that I can do to get rid of those messages?

Thanks in advance for your answer.

**Comment by ebaauw** [comment]
Make sure the lights are exposed correctly by deCONZ, including the `capabilities` for colour.  I guess these lights aren’t yet included in any oppressive the DDFs.  You should see a warning for that as well.

**Comment by BEskandari** [comment]
This is the deCONZ API results for the Hue Play:
_{
    "capabilities": {
        "alerts": [
            "none",
            "select",
            "lselect"
        ],
        "color": {
            "ct": {
                "max": 500,
                "min": 153
            },
            "effects": [
                "none",
                "colorloop"
            ],
            "modes": [
                "ct",
                "effect",
                "hs",
                "xy"
            ]
        }
    },
    "colorcapabilities": 31,
    "config": {
        "groups": [
            "0"
        ]
    },
    "ctmax": 500,
    "ctmin": 153,
    "etag": "0b629aae57dd30be28ec807a70c65dd3",
    "hascolor": true,
    "lastannounced": "2023-12-25T17:41:38Z",
    "lastseen": "2023-12-26T14:00Z",
    "manufacturername": "Philips",
    "modelid": "LCT024",
    "name": "Play 1",
    "state": {
        "alert": "none",
        "bri": 254,
        "colormode": "ct",
        "ct": 280,
        "effect": "none",
        "hue": 9390,
        "on": false,
        "reachable": true,
        "sat": 46,
        "xy": [
            0.402,
            0.3903
        ]
    },
    "swversion": "0x01002402",
    "type": "Extended color light",
    "uniqueid": "00:17:88:01:06:11:4b:8e-0b"
}_

**Comment by ebaauw** [comment]
So no `capabilities.color.xy` advertising the gamut.

**Comment by BEskandari** [comment]
@ebaauw  is there a way to adapt the DDF for this? or we can close the point.

**Comment by ebaauw** [comment]
That needs to be done in the deCONZ REST API plugin, see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki.

**Comment by BEskandari** [comment]
> That needs to be done in the deCONZ REST API plugin, see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki.

@ebaauw if you think is worthed I can submit the request on deCONZ REST API community, but I need your mentorship for describing the request. Let me know.
