### ISSUE TITLE
Ikea Fyrtur not working 

### ISSUE THREAD

**Issue by Bentrama** [ebaauw/homebridge-deconz#20]
Hello,

I have a weird issue with my IKEA fyrtur and the plugin.

I cannot control them through HomeKit, it says opening or closing but nothing moves.

when I try with the home+ app it’s the same thing never works.

I also tried with the web phoscon app but they don’t move neither.

I tried with the Deconz gui app and there they work correctly when sending an open/close command.

I tried to remove them from HomeKit accessory cache and restated but still the same issue.

What is weird is that they were working correctly 3 days ago and I didn’t change anything in the configuration.

I have also some zigbee lights connected through the plugin and they work fine 

can you help me with that ?

**Comment by ebaauw** [comment]
The plugin doesn’t send _Open_ nor _Close_, only _Go to Lift Percentage_.  Have you tried that command from the GUI?  Does the FYRTUR still have its configuration of the closed position?  Does it stop at the set position on _Close_, or does it continue moving?

**Comment by Bentrama** [comment]
It doesn’t work when I try to open or close with HomeKit/home+ or directly from the Homebridge accessory page. They only work from the Deconz GUI but I changed nothing.
And yes they still have their closed positioning correct

Envoyé de mon iPhone

**Comment by Bentrama** [comment]
And this is what the log in Homebridge looks : 
![BA368339-5528-47A7-9D4E-21E8D3DCBB7B](https://user-images.githubusercontent.com/92755428/155189820-56cc326d-afc0-4687-82a5-5f7c1713f553.png)

**Comment by ebaauw** [comment]
I leave the GUI running at all times, so it’s there when I need it.  Running deCONZ on a headless Raspberry Pi, and use screen sharing (VNC) to access the GUI.

I’m really curious if the blind reacts to _Go to Lift Percentage_.  Alternatively, you could try the `deconz` command-line utility and set `state.lift` (instead of `state.open`) through the API.  I don’t think I’ve ever seen that a device would be controllable through the GUI, but no longer through the API.

I find occasionally my FYRTUR locks up and stops reporting or even responding.  Usually fixed by a power-cycle (remove the battery for 10s).

**Comment by Bentrama** [comment]
They do do work fine when using these from the  GUI and also react when using « go to lift percentage on the gui 
![FD269962-B174-4974-B8F7-78EC30924597](https://user-images.githubusercontent.com/92755428/155195201-cd903347-ae19-438f-81fa-bffd1987f9a7.jpeg)

I dont exactly know nos to try through the API, would you tell me ?

**Comment by ebaauw** [comment]
Issue `deconz put /lights/`_id_`/state '{"lift": 0}'` on the command line, substituting the resource id of the FYRTUR (which you can see in Eve in the _Device Settings_ service).

**Comment by Bentrama** [comment]
I get this when trying:
![1B62338A-378F-4557-ABE2-87D883836EE7](https://user-images.githubusercontent.com/92755428/155198442-f1b5f13b-a58c-4e5d-a2bc-f9bceea6199a.png)

**Comment by ebaauw** [comment]
If you're not running deCONZ on port 80, you need to specify the port: `deconz -H localhost:`_port_` put ...`.

If you're not running Homebridge on the same host as deCONZ, you need to specify the hostname and port through `-H`.  Also, you need to unlock the gateway and run `deconz -H ... getApiKey` once.  Issue `deconz -h` for help.

**Comment by Bentrama** [comment]
Im running deconz on my raspberry which also hosts homebridge on the official homebridge raspbian image.
I tried what you asked and was able to get the API KEY but the command does ont work.
Here is the return :
![C69A69C5-1B5A-4C43-9675-51B4DEC82B19](https://user-images.githubusercontent.com/92755428/155210765-622c493e-96c1-4281-aaf0-6dc06083c27a.png)

**Comment by ebaauw** [comment]
If it works in the GUI, but not here, it’s between the REST API plugin and the deCONZ core.  I don’t think I’ve seen that before.  Did you try and power cycle the FYRTUR?  And restart deCONZ?  Do you see any errors in the deCONZ log?

**Comment by Bentrama** [comment]
I managed to make them work with Home app again, they open and close normally.

but there is still one thing, Home app and home+ app report them as closed even when they are fully open.

**Comment by Bentrama** [comment]
What changed ? 
I did leave the Deconz GUI open and not using the Deconz headless.

Yes Deconz doesn’t refresh automatically, after opening the stores If I go to the deconz gui and read the value HomeKit sees it at open. It’s the same when I close them again they stay at “open” state and if I read the value HomeKit sees them as closed. 

With thé Homebridge-hier plugin I used to see the percentage moving 5% by 5% when they were closing or opening but here no.

I will try to power cycle the fyrtur now and tell you if it’s good

**Comment by Bentrama** [comment]
Ok I just power cycled them.

but issue is a bit different.

when I open them the home app says « opening » then in the middle at about 50% opening home app reports « opened at 50% » then they continue to open but home app switch to « closing »’and says closed when they are fully open.

I did remove the batteries for about 10 seconds

**Comment by Bentrama** [comment]
I think I found something in Homebridge, you can see in this picture Homebridge says :"target posisition 55%" could it be the problem ? and how to correct it ?
<img width="1912" alt="Capture d’écran 2022-02-23 à 17 42 44" src="https://user-images.githubusercontent.com/92755428/155365901-b086a4db-c65b-498f-b106-4d6a26bb08c0.png">

**Comment by Bentrama** [comment]
Im at V0.0.13

i managed to correct that target position, it was the slider in the home+ app for the fyrtur that was at this position.

But still, after rebooting completely the pi the issue is still there, at about half of the course when opening it changes to closing by itself but continues to open and when closing it changes to opening, I don’t know where that comes from

also my deconz version is : 2.14.01 / 06/02/2022
And the conbee firmware is : 26720700

**Comment by ebaauw** [comment]
There’s a fundamental design mismatch between the REST API and HomeKit.  Unlike HomeKit, which has separate characteristics for _Current Position_, _Target Position_, and _Position State_ (opening, closing, stopped) the API only reports the _Current Lift Percentage_.  Also, Apple’s Home app ignores _Position State_, and displays the state based on _Current Position_ vs _Target _Position_.

Homebridge deCONZ needs to compute the appropriate values for _Target Position_ and _Position State_, based only on _Current Lift Percentage_.  That’s relatively easy when you set _Target Position_ from HomeKit, but more complex when the blind is also controlled by other API clients, or by the Open/Close Remote, controlling the blind directly.  Also, you don’t want Home to continue to report that the blind is moving, when a report is missed.  To achieve this, Homebridge deCONZ updates _Target Position_ to _Current Position_ when it receives a report while it hasn’t initiated a move recently (assuming someone else started the move).

The FYRTUR takes quite some time to fully open or close, during which It reports its current position several times.  I think the 15s timeout for a recently initiated move might be too aggressive for your situation, causing the _Target Position_ to be set to _Current Position_ while the blind is still moving.  How long does your FYRTUR take to move from fully closed to fully opened?  What height does it cover?

**Comment by Bentrama** [comment]
Ok I get that but it was working fine before that’s why I don’t understand, also file with the hue plugin.

It takes about 25 seconds for the blind to fully open and the length I would say is about 1 meter and a half more or less.

![10844C55-8FEC-4961-B060-F58CF6F7B234](https://user-images.githubusercontent.com/92755428/155379491-943377f0-c60c-492b-ae18-adce129aaf56.jpeg)

**Comment by Bentrama** [comment]
So there’s nothing I could do about it right ? That’s weird as it worked fine with the deconz plugin before.

is there a way to change that 15sec time ? 

Is it why it changes from « opening » to « closing » in home app during operation ?

**Comment by ebaauw** [comment]
“Before” as in v0.0.12?

I’ll double the 15s in the next release, also made some more changes already to fix another bug in the logic.

As I said, Home displays the state based on the _Current Position_ and _Target Position_ values, instead of on _Position State_.  It’s probably just as confused as I am…

**Comment by Bentrama** [comment]
Maybe, we don’t open them often so it might be from the last version but I’m not a 100% sure.

Yes i understand what you said, I will wait for the next release and see if it’s better ! 

My goal was to ditch all those hubs and have only a raspberry but I’m about to put back these one on the IKEA hub as I can’t fix them, it’s ok for me but for the wife you know it has to work haha.

Maybe I’ll try to completely remove them from deconz and re-pair I don’t know but I’ll wait for your next release before.

But thanks a lot for your help sir !

**Comment by ebaauw** [comment]
> I’ll double the 15s in the next release, also made some more changes already to fix another bug in the logic.

Damn.  Didn't make it in v0.0.14.  Sorry for that.

**Comment by Bentrama** [comment]
Hello,
I just updated and tested them, looks like they work normally for now 😉 

thanks
