### ISSUE TITLE
Exposed by legacy code

### ISSUE THREAD

**Issue by KatyPurry** [ebaauw/homebridge-deconz#200]
Hello,
I'm running Homebridge for months without problem. By curiosity I checked logs after a restard and a lot of my accessories have this line : 

`[12/31/2023, 10:47:30 PM] [deCONZ-alex] Phoscon-GW: warning: TS0201 cuisine: exposed by legacy code`

Should I be worried? 
Thank you and happy new year

**Comment by ebaauw** [comment]
See #180.  I changed the text of the warning in v1.0.8, see https://github.com/ebaauw/homebridge-deconz/releases/tag/v1.0.8.

**Comment by Zazou89** [comment]
I have v1.0.9, should I be concerned ?

**Comment by KatyPurry** [comment]
I have v1.0.9, should I be concerned ?

**Comment by ebaauw** [comment]
Again, see https://github.com/ebaauw/homebridge-deconz/issues/180#issuecomment-1781846566

**Comment by Zazou89** [comment]
Thank you ! I didn't see the comment.

**Comment by KatyPurry** [comment]
Thank you, I didn't see the mention, i just checked the changelog.
