### ISSUE TITLE
Styrbar switch in homebridge but not in homekit

### ISSUE THREAD

**Issue by avweenen** [ebaauw/homebridge-deconz#201]
The Tradfri E2002 Styrbar switch form ikea is working on the Conbee2 and showing in homebridge. But not in homekit so i cannot attach a scene in it. Is it possible to link it to homekit by homebridge?

**Comment by ebaauw** [comment]
Not sure I understand what you’re asking.  You pair the bridge accessory as exposed by Homebridge to HomeKit, after which all bridged accessories exposed by plugins appear in HomeKit as well.  Homebridge deCONZ exposes the Styrbar as any other bridged accessory.  If it appears in the Homebridge UI under _Accessories_ and if you have paired Homebridge to HomeKit, the Styrbar should be visible in HomeKit as well.

**Comment by avweenen** [comment]
The Styrbar is connected to deCONZ and is visible in homebridge. When i push a button i can see it in the log of homebridge. The buttons are also visible in accessories of homebridge. But it is not recognized in homekit. I also tried to use deCONZ as a child bridge, ad homekit accepts the child bridge. But the Styrbar buttons are not shown in homekit and i can not find them when i try to make a new automation.
I also have the dummy-switch plugin in homebridge and this function works fine, so it seems homebridge is not passing the deCONZ to homekit?

**Comment by ebaauw** [comment]
Did you pair the child bridge with HomeKit?

**Comment by avweenen** [comment]
Yes, i did.
![IMG_6602](https://github.com/ebaauw/homebridge-deconz/assets/76393557/cd4eaf98-1b1b-4b21-b109-f56549511712)

**Comment by avweenen** [comment]
But when i click accessories the list is empty.
![IMG_6603](https://github.com/ebaauw/homebridge-deconz/assets/76393557/ab4701c1-0c8b-4849-b965-baf4bf0f3f59)

**Comment by ebaauw** [comment]
Apple's Home app ~~sucks~~ is somewhat confusing; it won't show stateless programmable switches in that view.  Best use a decent HomeKit app, or look in the rooms view.
