### ISSUE TITLE
ZHAThermostat - display temperature of external sensor

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-deconz#202]
I am using a Ubisys H1 thermostat. In the latest firmware (1.5 / 1.5.1) they added the ability to bind external sensor to the thermostat. I bound a SONOFF sensor and this works great. But in Home I still see the temperature of the H1 internal sensor. It looks like they don't disable it and don't expose the temperature of the external sensor. So it would be nice to link the sensor to the thermostat in homebridge-deconz, too. Could you add this?

<img width="608" alt="1216-1332-max" src="https://github.com/ebaauw/homebridge-deconz/assets/869857/41719252-2e1d-417b-9dde-a3e80d4a579e">

(this could be one item because the Thermostat uses the temperature of the sensor)

**Comment by ebaauw** [comment]
> they added the ability to bind external sensor to the thermostat.

That's a standard Zigbee feature, but not exposed by the deCONZ REST API.  Homebridge deCONZ has no way of knowing whether such binding exists.

> So it would be nice to link the sensor to the thermostat in homebridge-deconz, too. Could you add this?

No.  I won't be combining multiple devices into a single accessory.  And even if I would consider that, Homebridge deCONZ wouldn't know when to do this, as it has no knowledge of the Zigbee bindings.

> It looks like they don't disable it and don't expose the temperature of the external sensor.

Maybe there's a setting on the H1 to report the temperature of the external sensor instead of the internal sensor?  Otherwise: How does deCONZ expose the H1?  If the temperature of the external sensor is exposed through some other REST API attribute, it might use it en lieu of the internal `state/temperature`.  I cannot expose both on a single accessory, as that would break Eve history for the thermostat.

**Comment by jan666** [comment]
I think even deCONZ does not know there is a binding (I never found a way to view all bindings of a device)?

The H1 DDF was done for firmware version 1.4.0 and the binding feature was added in 1.5.0. It is exposed like this:

```
{
  "config": {
    "battery": 100,
    "group": "20006",
    "heatsetpoint": 1700,
    "mode": "heat",
    "offset": 0,
    "on": true,
    "reachable": true,
    "schedule": {
      "W127": [
        {
          "heatsetpoint": 1400,
          "localtime": "T00:00"
        },
        {
          "heatsetpoint": 1700,
          "localtime": "T07:00"
        },
        {
          "heatsetpoint": 2000,
          "localtime": "T16:00"
        },
        {
          "heatsetpoint": 1400,
          "localtime": "T20:30"
        }
      ]
    },
    "schedule_on": true,
    "unoccupiedheatsetpoint": 1600
  },
  "etag": "992b61a30a01a2137e2928aec4823b05",
  "lastannounced": null,
  "lastseen": "2024-01-04T06:17Z",
  "manufacturername": "ubisys",
  "modelid": "H1",
  "name": "Thermostat DG Erik",
  "state": {
    "lastupdated": "2024-01-04T06:17:49.094",
    "on": false,
    "temperature": 2200,
    "utc": "2024-01-04T06:17:43Z",
    "valve": 0
  },
  "swversion": "1.5.1",
  "type": "ZHAThermostat",
  "uniqueid": "00:1f:ee:00:00:00:98:af-01-0201"
}
```

The real temperature from the external SONOFF sensor is

```
  "name": "Sensor DG Erik",
  "state": {
    "lastupdated": "2024-01-04T06:18:53.965",
    "temperature": 1786
  },
```

I already looked at the clusters listed in the deCONZ UI but I can't find anything releated to the external sensor. Its only the display of the device that shows it. I don't know if there are clusters that deCONZ does not show?

Is there a best practice how other manufacturer expose the external temperature? Maybe I could Ubisys ask to implement it like it.

**Comment by jan666** [comment]
I already contacted Ubisys and they sent me their in-draft technical reference.

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/67491a5f-7471-483d-bfad-4efa7ecf8cbc)

This is the temperature I am looking for:

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/518e0400-c54a-4983-bf4b-4dce361238b4)

So I guess the correct way is to expose this as `config/externalsensortemp`? And homebridge-deconz could use this as current temperature instead of `state/temperature`?

**Comment by ebaauw** [comment]
> The question was to ask if that could be done manually. Something like linking 2 sensors together via resource-item (in homebridge-hue times). Because you're already merging multiple sensor endpoints to one accessory (temperature and humidity for example).

Those are resources for the same device.  You’re asking to combine (resources for) multiple devices into one accessory.

> So I guess the correct way is to expose this as `config/externalsensortemp`? And homebridge-deconz could use this as current temperature instead of `state/temperature`?

Yes. I think it should probably be a `state` attribute, though.  The resource item might already exist and be used for some other TRVs.  https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/config_externalsensortemp_item.json

**Comment by jan666** [comment]
I can't really get it to work. I tried 

```
        {
          "name": "config/externalsensortemp",
          "refresh.interval": 3660,
          "parse": {
            "at": "0x0013",
            "cl": "0x0201",
            "ep": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "default": 0
        },
```

but it always stays at

```
{
  "config": {
    "battery": 90,
    "externalsensortemp": 0,
```

this DDF stuff is a little bit confusing...

**Comment by ebaauw** [comment]
I think you need to add the manufacturer code.

**Comment by jan666** [comment]
You're right (again)

Now I have

```
{
  "config": {
    "battery": 100,
    "externalsensortemp": 1804,
    "group": "20006",
    "heatsetpoint": 1400,
    "mode": "heat",
    "offset": 0,
    "on": true,
    "reachable": true,
    "schedule": {
      "W127": [
        {
          "heatsetpoint": 1400,
          "localtime": "T00:00"
        },
        {
          "heatsetpoint": 1700,
          "localtime": "T07:00"
        },
        {
          "heatsetpoint": 2000,
          "localtime": "T16:00"
        },
        {
          "heatsetpoint": 1400,
          "localtime": "T20:30"
        }
      ]
    },
    "schedule_on": true,
    "unoccupiedheatsetpoint": 1600
  },
  "etag": "8e666c8d585b82ea807a8f5fe711daae",
  "lastannounced": null,
  "lastseen": "2024-01-05T05:51Z",
  "manufacturername": "ubisys",
  "modelid": "H1",
  "name": "Thermostat DG Erik",
  "state": {
    "lastupdated": "2024-01-03T11:45:26.565",
    "on": false,
    "temperature": 2200,
    "utc": null,
    "valve": 58
  },
  "swversion": "1.5.1",
  "type": "ZHAThermostat",
  "uniqueid": "00:1f:ee:00:00:00:98:af-01-0201"
}
```

**Comment by jan666** [comment]
Before: 

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/b5de0fad-6710-427e-9790-060a564a9371)

After:

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/54103cfa-3a04-4326-b910-94e56a2cd43b)

Works!

![image](https://github.com/ebaauw/homebridge-deconz/assets/869857/cd46af14-95de-4542-b42e-8260619d8d4a)

**Comment by ebaauw** [comment]
In v1.0.10.
