### ISSUE TITLE
Didn't get Phoscon (RaspbeeII) work with homebridge-deconz

### ISSUE THREAD

**Issue by ellzzett** [ebaauw/homebridge-deconz#204]
I have an issue using homebridge-deconz together with raspbeeII.

I freshly installed homebridge-deconz and raspbeeII.
After that I restart the RaspberryPi.

Log says:

```
[04/01/2024, 14:00:40] [deCONZ] Phoscon-GW: websocket connected to ws://127.0.0.1:4531"
[04/01/2024, 14:00:37] [deCONZ] hardware: Raspberry Pi 2B 1.1 (1GB)
[04/01/2024, 14:00:37] [deCONZ] os: Raspbian GNU/Linux 11 (bullseye) [32 bit]
[04/01/2024, 14:00:37] [deCONZ] restored 1 accessories from cache
[04/01/2024, 14:00:37] [deCONZ] ui server: listening on http://127.0.0.1:36097/
[04/01/2024, 14:00:40] [deCONZ] Phoscon-GW: websocket connected to ws://127.0.0.1:4531"
```

But when using the Phoscon app I see port **4530** instead **4531**.

Even the virtual daylight sensor is not available in Homebridge.
Any advice whats going wrong?

Regards

**Comment by ebaauw** [comment]
Looks like Homebridge deCONZ connected to deCONZ alright, or it wouldn't know to use port 4531 for the websocket notifications.

> But when using the Phoscon app I see port 4530 instead 4531.

For the websocket?

**Comment by ellzzett** [comment]
> Looks like Homebridge deCONZ connected to deCONZ alright, or it wouldn't know to use port 4531 for the websocket notifications.
> 
> > But when using the Phoscon app I see port 4530 instead 4531.
> 
> For the websocket?

When accessing phoscon app I need to use the ip of the raspberry together with port 4530 —> 192.xxx.x.xxx:4530

**Comment by ebaauw** [comment]
That’s the port of the web server, serving the API.

**Comment by ellzzett** [comment]
Understood. But why I can‘t see the virtual daylight sensor in homebridge?

**Comment by ebaauw** [comment]
Did you expose it?  By default, only Zigbee devices are exposed automatically.

**Comment by ellzzett** [comment]
> Did you expose it? By default, only Zigbee devices are exposed automatically.

Didn‘t no that. Thanks for your help!
