### ISSUE TITLE
otau: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by BEskandari** [ebaauw/homebridge-deconz#205]
Hi Erik,
when I use to download the latest firmware through the otau command, i get the below errors for a bunch of Hue devices.

> pi@homebridge:~/otau$ otau
otau: meethue: request 1: GET /ZGB_100B_0100/60ecddb6-be67-4c91-b4cb-a87d0f392473/ConnectedLamp-TI-Target_0012.sbl-ota
otau: warning: meethue: request 1: error: self-signed certificate in certificate chain
otau: meethue: request 2: GET /ZGB_100B_0103/5509a154-fe62-4cd3-bb11-19b46da0e074/LivingColors-Hue-Target_0012.sbl-ota
otau: warning: meethue: request 2: error: self-signed certificate in certificate chain
otau: meethue: request 3: GET /ZGB_100B_0104/3d70cb22-87b2-4f1b-b7e8-3659d5feb9ed/ConnectedLamp-Atmel-Target_0012.sbl-ota
otau: warning: meethue: request 3: error: self-signed certificate in certificate chain

And the files are not downloaded!

**Comment by ebaauw** [comment]
Looks like Signify installed a new, now self-signed certificate to their firmware server on Dec 28.  Above commit will cause `otau` to accept the self-signed certificate, but it doesn't check it.  Use at your own risk.

**Comment by ebaauw** [comment]
In v1.0.10.
