### ISSUE TITLE
Mystery Homebridge Button

### ISSUE THREAD

**Issue by rhwood** [ebaauw/homebridge-deconz#206]
There is a button _Homebridge Button_, which appears to have been created by this plugin (as I can't find it in the Phoscon App).

Every minute, I am getting this in the logs
```
[06/01/2024, 12:32:59] [deCONZ] Homebridge Button: Programmable Switch Event: Single Press
```

What is this device (it seems to claim be the Raspbee II, but that has no buttons)?

**Comment by ebaauw** [comment]
See Wiki, https://github.com/ebaauw/homebridge-deconz/wiki/Gateway-Accessory, and closed issues.

**Comment by microfx** [comment]
> See Wiki, https://github.com/ebaauw/homebridge-deconz/wiki/Gateway-Accessory, and closed issues.

But this is not fixing anything. I feel at this point this could get incorporated into the code to not spam everyone's logs?
