### ISSUE TITLE
request 1: /: api error 1: unauthorized user

### ISSUE THREAD

**Issue by qwertz2021** [ebaauw/homebridge-deconz#209]
Hello guys,

following situation:

- fresh install of my homebridge (using my homebridge backup) on my raspberry 4
- install deCONZ via sudo hb-config
- plug the conbee2 USB-stick into the raspberry

Now I get these message:

[04/02/2024, 13:37:30] [deCONZ] Phoscon.gateway: request 1: GET /
[04/02/2024, 13:37:30] [deCONZ] Phoscon.gateway: warning: request 1: /: api error 1: **unauthorized user**
[04/02/2024, 13:37:30] [deCONZ] 1 gateways
[04/02/2024, 13:37:30] [deCONZ] created debug dump file /var/lib/homebridge/homebridge-deconz.json.gz

No devices are visible in the homebridge ui and in Apple Home but I can see them in the Phoscon App.

Any ideas to fix this **unauthorized user** issue?

- OS: Debian GNU/Linux Bookworm (12)
- Node.js Version v20.11.0
- Conbee2 gateway version: 2.25.1 
- Conbee 2 firmware version: 26780700

**Comment by qwertz2021** [comment]
Add: I seen this thread but I don't know, what's to do in the Eve App: https://github.com/ebaauw/homebridge-deconz/issues/50 

_Best unset Expose (that should clear the old API key), and, after a half a minute or so, set it again. Homebridge deCONZ will ask you (in the log) to unlock the gateway, so it can obtain a new API key._

What means "Expose"?

**Comment by qwertz2021** [comment]
There is no "Expose" option in the Eve App: 
![Uploading IMG_9276.jpg…]()

**Comment by qwertz2021** [comment]
There is no "Expose" Option in the Eve app:

![IMG_9276](https://github.com/ebaauw/homebridge-deconz/assets/81743856/3c1ef916-4cec-4bfd-a676-381d9a49e19e)

**Comment by qwertz2021** [comment]
There is no "Expose" Option in the Eve app:

![IMG_9276](https://github.com/ebaauw/homebridge-deconz/assets/81743856/254636f3-fd95-4ff6-917c-929caed9643e)

**Comment by ebaauw** [comment]
Looks like you backed up/restored Homebridge deCONZ, but not deCONZ itself.  The (restored) API key that Homebridge deCONZ used for the previous deCONZ installation is not known to the new deCONZ installation.  Indeed, the remedy is to un-expose the gateway, and re-expose it, so Homebridge deCONZ will forget the restored API key and request a new one.

Dynamic settings are now exposed through a separate API, rather than through HomeKit, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.  See https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#example-6 how to un-expose the gateway.

**Comment by qwertz2021** [comment]
@ebaauw 

Thanks for your explanation.

Solved with

```
ui -D put / ‚{“expose“: false}‘
ui -D put / ‚{“expose“: true}‘
```

...Conbee2 "App verbinden"/restart Homebridge -> et voilà

Thread can be closed.

**Comment by qwertz2021** [comment]
One question left. 

> Looks like you backed up/restored Homebridge deCONZ, but not deCONZ itself. The (restored) API key that Homebridge deCONZ used for the previous deCONZ installation is not known to the new deCONZ installation.

For the next time: The homebridge backup does not include the deCONZ part. How can I backup the API key from my new deCONZ installation or is this not needed?

**Comment by ebaauw** [comment]
You need to backup and restore deCONZ, through the Phoscon app.

**Comment by qwertz2021** [comment]
I had done that, so it's not clear to me why it happened...
