### ISSUE TITLE
SOMRIG IKEA only on botton in HK

### ISSUE THREAD

**Issue by Donni1966** [ebaauw/homebridge-deconz#210]
Hi, 
the relativ new IKEA Botton SMORIG is in decent a two Botton Switch with 
1 short press Number 1000/1002 
2 short press and 1000/1004
long press 1000/1001/1003
and the secound with 200X

In HK : 

![Bildschirmfoto 2024-02-07 um 19 23 58](https://github.com/ebaauw/homebridge-deconz/assets/61660957/3e19099c-2bfa-4317-9936-ca0838eb2f93)
![Bildschirmfoto 2024-02-07 um 19 23 48](https://github.com/ebaauw/homebridge-deconz/assets/61660957/83180e4f-ab96-44f9-8f4f-28a0f0d86c46)

any idea? 
need logs?

**Comment by Donni1966** [comment]
Fine - thanx.

**Comment by mariomaz87** [comment]
I opened the issue section to post about the same thing, thanks!

**Comment by ebaauw** [comment]
In v1.0.10.
