### ISSUE TITLE
[deCONZ] Homebridge Button: Programmable Switch Event: Single Press

### ISSUE THREAD

**Issue by microfx** [ebaauw/homebridge-deconz#214]
Hey Erik, 

I know this has been asked 1000 times and you have pasted 1000 times the wiki link. I have no clue where to set what. Your wiki might be an excellent library for you to read up on stuff but you have to remember that your brain interpolates a lot because you probably know every single text character in this project.

Could you maybe give a few more tips / instructions where to change what? I now tried it this way: Clicked in Homebridge on the Homebridge Deconz 

<img width="816" alt="Bildschirmfoto 2024-03-04 um 22 17 18" src="https://github.com/ebaauw/homebridge-deconz/assets/37987212/7799af2c-1d48-4978-91f4-fc4383898363">

And then tried to add the line here (I tried to orient it from one of the examples where it's under the "name"

<img width="604" alt="Bildschirmfoto 2024-03-04 um 22 17 51" src="https://github.com/ebaauw/homebridge-deconz/assets/37987212/6d1dfa09-76cb-4c3e-9296-2065d4b4af3c">

This doesn't work.

Any clue? 

Cheers

**Comment by ebaauw** [comment]
As described in the Wiki, dynamic settings aren't in config.json.  Instead, use the `ui` tool to change these.

**Comment by microfx** [comment]
it's super unclearly stated in the wiki tbh - but as said that's a perspective thing... Inverse Dunning Kruger Effect maybe or something 😀 No offense.

I will look into it again. 

You would help more people if you would just give the answer since google is now thinking this is an answer but it's not helpful for the majority. 

I will try to write the solution to this problem (I am fearing lots of obstacles on the way as per usual when a dev says "just do this" and I am 3 days into learning how to compile the multitude of libraries with different toolchains 😂)

**Comment by microfx** [comment]
The magic command for everyone else caring for a solution:

Open up Homebridge UI in the browser, click on the ... and then Console. Then type into the CLI: 
```
ui put / '{"periodicEvents": true}'
```

Or if you want to do it over SSH (in my case the path is like this):

```
/var/lib/homebridge/node_modules/.bin/ui put / '{"periodicEvents": true}'
```
