### ISSUE TITLE
TS000F - Switching between Lights and Fan Type

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-deconz#215]
Hi Erik,

I hope you're doing well. I could use your expertise on something:

I recently installed a Zigbee relay (https://www.amazon.de/dp/B0BQB5VBSP?ref=ppx_yo2ov_dt_b_product_details&th=1). 

It seems to be working fine, and I've managed to integrate it into my smart home setup. However, I'm encountering a problem: I want to use one gang to switch a fan, but I can't seem to change the device type to "Fan" like I can with other plugs in the Home app. 
I'm not sure if this is related to homebridge-deconz or if there's another issue at play. 
Additionally, I've noticed that the power metering feature isn't showing up in the EVE app, although I can live with that: )

Do you have any ideas on how I can address these issues?

Thanks in advance,
Paul

**Comment by ebaauw** [comment]
Is this device exposed by deCONZ using a DDF, or by legacy code?

> I'm encountering a problem: I want to use one gang to switch a fan, but I can't seem to change the device type to "Fan" like I can with other plugs in the Home app.

This is a feature of HomeKit, not of the accessory.  For service types _Outlet_ and _Switch_, Home displays a _Display As_ option on the _Accessory Settings_.  You might need to select _Show as Separate Tiles_ first, not sure.  Eve displays this under _Types and Names_ in its _Accessory Settings.  It shows a row per service in the popup.  However, if the relay is exposed as _Lightbulb_, you won't see such option.

> Additionally, I've noticed that the power metering feature isn't showing up in the EVE app

For that, the deCONZ API needs to expose the ZHAConsumption and ZHAPower `sensors` resources.

**Comment by beatpaul** [comment]
I tried both first it was using legacy code, then I tried to create a DDF File ("Edit DDF -> save the file")

I now tired to set it as outlet ( = output ?) in the DDF an reloaded it by restarting my pi:

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_m8f3z8ju",
  "modelid": "c",
  "product": "TS000F",
  "sleeper": false,
  "status": "Silver",
  "path": "/devices/ts000f_PT1.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

nothing changed unfortunately --> do I have to reload the device somehow in the home app ?

**Comment by ebaauw** [comment]
I think you need to un-expose and re-expose it in Homebridge deCONZ.

**Comment by beatpaul** [comment]
sorry for bothering with such basic things ... but I cannot find the expose option ... how can I do that ? (I remember the option in Eve App tough)

**Comment by ebaauw** [comment]
No, that was many versions ago.  It's through the `ui` command-line utility now, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration.  It's something like: `ui put /devices/`_deviceID_` '{"expose": false}'` followed by `ui put /devices/`_deviceID_` '{"expose": false}'`, substititing _deviceID_ with the relay's MAC address.

**Comment by beatpaul** [comment]
that did the thing!
 thx a lot! 
( -->second command  I used  `'{"expose": true}'` of course :)

**Comment by ebaauw** [comment]
Of course, updated my comment.
