### ISSUE TITLE
Conbee II on hoobs .. this "Error" - what does it mean ?? Comes every min..

### ISSUE THREAD

**Issue by The-Paw** [ebaauw/homebridge-deconz#219]
29.5.2024, 09:33:11DeconzdeCONZPhoscon: Programmable Switch Event: Single Press
29.5.2024, 09:34:11DeconzdeCONZPhoscon: Programmable Switch Event: Single Press
29.5.2024, 09:35:11DeconzdeCONZPhoscon: Programmable Switch Event: Single Press
29.5.2024, 09:36:11DeconzdeCONZPhoscon: Programmable Switch Event: Single Press
29.5.2024, 09:37:11DeconzdeCONZPhoscon: Programmable Switch Event: Single Press
29.5.2024, 09:37:11DeconzdeCONZPhoscon: Programmable Switch Event: Double Press
29.5.2024, 09:37:21DeconzdeCONZWARNUNGPhoscon: warning: unlock gateway and set expose to obtain an API key

**Comment by ebaauw** [comment]
See closed issues,

**Comment by The-Paw** [comment]
@ebaauw sorry .. can´t find any "fix" for it :-((( What should I change ??
