### ISSUE TITLE
Strange behavior with adaptive lighting

### ISSUE THREAD

**Issue by MSL-DA** [ebaauw/homebridge-deconz#222]
Something strange happens when I adjust the brightness of IKEA lamps (Only when adaptive lighting is activated). This only applies to my IKEA lamps, and not to my lamps from Philips. I'm on iOS 18 beta3, tvOS 18 beta3 on my homepods and apple tv

It happens on GW version 2.27.5, but also on version 2.26.3

The lamps are slow to update. If I set a lamp to 65%, the setting "jumps" back to the last setting, for example 85%

**Comment by ebaauw** [comment]
Do you see the same on non-beta versions of iOS and tvOS?  If not, better wait for the released versions.  Otherwise, I need more information to comment on this.  Please attach the debug dump file, and capture and attach a debug log file, capturing the brightness change of a Philips light and of an IKEA light.

**Comment by MSL-DA** [comment]
I'll look into it when I have access to a non-beta device. But it surprises me that it applies to all my IKEA lamps and something I haven't noticed until now

**Comment by ursusHU** [comment]
I have the very same issue with non-beta devices and ikea bulbs. Very slow the brightness setting jumps back and forth. And even it is changing automatically for some reason. If I correct it after turning off the adaptive light setting to 100% and then turn on adaptive setting again the brightness automatically changes to another level.

**Comment by ursusHU** [comment]
Here everything was set to 100%
![IMG_8462](https://github.com/user-attachments/assets/cad3e94c-2ace-4c30-8a48-5bfe01e53fde)

**Comment by MSL-DA** [comment]
> Do you see the same on non-beta versions of iOS and tvOS? If not, better wait for the released versions. Otherwise, I need more information to comment on this. Please attach the debug dump file, and capture and attach a debug log file, capturing the brightness change of a Philips light and of an IKEA light.

Can I contribute anything to troubleshoot or do you know where to look?

**Comment by ursusHU** [comment]
Is this the same problem?
https://github.com/ebaauw/homebridge-deconz/issues/171

**Comment by ebaauw** [comment]
> Is this the same problem?

Could very well be, I suppose.  What IKEA bulbs are you using?  Are they exposed through DDF or legacy code?  Do they have the IKEA firmware bug?

**Comment by ursusHU** [comment]
I have the follwoing IKEA bulbs:
    "manufacturer": "IKEA of Sweden",
    "model": "TRADFRI bulb E27 WW 806lm",
    
    "manufacturer": "IKEA of Sweden",
    "model": "TRADFRI bulb E27 WS opal 1000lm",
    
    "manufacturer": "IKEA of Sweden",
    "model": "TRADFRI bulb GU10 WS 400lm",

    "manufacturer": "IKEA of Sweden",
    "model": "TRADFRIbulbE14WSglobeopal470lm",

I have a headless installation of deCONZ so I don't use DDF currently.

I'll check the description in the other issue.

**Comment by ursusHU** [comment]
Downloaded DDF files from https://deconz-community.github.io/ddf-tools/#/store/search
Will see if the behavior is changing.

**Comment by MSL-DA** [comment]
I am closing this as it is a result of firmware bug and missing DDF
