### ISSUE TITLE
Adaptive lighting brightness adjustment

### ISSUE THREAD

**Issue by ursusHU** [ebaauw/homebridge-deconz#224]
Hello,
would it be possible to have a similar functionality like the brightness adjustment for adaptive lightning in Homebridge-hue? HomeKit doesn’t really handles this very well, my lights are almost white even during the night. In Homebridge-Hue this setting was very helpful to set the color of white accordingly to my preference.
![IMG_8500](https://github.com/user-attachments/assets/000925d4-c1ec-44fd-94cf-18642215fecb)
Thank you in advance for your answer.

**Comment by ebaauw** [comment]
It's already there, under the dynamic settings of the gateway, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#settings.

**Comment by ursusHU** [comment]
Thanks a lot found it :)
