### ISSUE TITLE
TypeError: DeconzService.Battery is not a constructor with v1.0.14

### ISSUE THREAD

**Issue by kolorfilm** [ebaauw/homebridge-deconz#226]
Hi there,

after the update to v1.0.14 I got a type error with an accessory.

![image](https://github.com/user-attachments/assets/bb04464c-1bf8-4aa6-8475-eef343111f91)

With the previous version everything works.

**Comment by smart7324** [comment]
I'm having the same issue on version 1.0.14

**Comment by lhari84** [comment]
Same here. Went back to 1.0.13 for now, just to avoid any potential issues.

**Comment by ebaauw** [comment]
Which accessory is this?  Please provide the debug dump file.

**Comment by lhari84** [comment]
> Which accessory is this? Please provide the debug dump file.
> 
> Probably caused when deCONZ reports `config.battery` as `null`.

I can't find out which deievice causes the issue, but here i provide the dump file: 

[homebridge-deconz.json.gz](https://github.com/user-attachments/files/16732685/homebridge-deconz.json.gz)

**Comment by ebaauw** [comment]
Thanks.  No `null` values for `config.battery`, but I do see the code fails to recognise that a device has a battery when it only has one resource, which is the case for your wireless switches.

**Comment by ebaauw** [comment]
Could you please try beta v1.0.15-0?

**Comment by lhari84** [comment]
Looks good, no errors or warnings anymore with v1.0.15-1. 
Thank you very much for your work and support!

**Comment by ebaauw** [comment]
Published v1.0.15 and unpublished v1.0.14.

**Comment by kolorfilm** [comment]
Works for me as well, thanks for the fast fix 🙏🏻.
