### ISSUE TITLE
Configured Name: warning: 2 listeners since v1.0.14

### ISSUE THREAD

**Issue by lhari84** [ebaauw/homebridge-deconz#227]
Hi, 
I get this warning for several Hue switches and wall modules: 
First thought it was because of invalid characters like "/" in name, but after removing, the warnings still pop up in logs.

![image](https://github.com/user-attachments/assets/544ca12b-55ba-40d6-9c49-c9f501b26350)

**Comment by lhari84** [comment]
> Multiple listeners typically are cause by another error while trying to expose a device. Are these devices which fail to be exposed because of the "TypeError: DeconzService.Battery is not a constructor" (see #226)?
> 
> If not, please indicate which devices these are, and show the full log.

I can't tell which devices cause "TypeError: DeconzService.Battery is not a constructor" in my case, but I've provided debug dump. Hope it helps.

**Comment by ebaauw** [comment]
This was indeed a side effect of #226 and should be solved in v1.0.15.
