### ISSUE TITLE
Feature Request: Expose ZHAWater as Contact Sensor

### ISSUE THREAD

**Issue by jan666** [ebaauw/homebridge-deconz#230]
Hello,

could you add an option (like Light -> Valve) to expose a ZHAWater sensor as Contact Sensor? 

Background: I have a BADRING Water Leakage Sensor connected to a small magnetic reed contact. I want to put the BADRING in my letterbox and install the reed contact to the slit.

**Comment by ebaauw** [comment]
No, that's beyond the scope of Homebridge deCONZ.

You could create a CLIPOpenClose sensor, which Homebridge deCONZ exposes as Contact sensor, and use some deCONZ rules to mirror the BADRING's state to the CLIP sensor.

**Comment by jan666** [comment]
Ah, thanks for the hint. Solving this in deCONZ is even better :) Did not know this is possible

**Comment by jan666** [comment]
Just for the sake of dokumenting this:

Create the CLIPOpenClose sensor

`curl -vv -XPOST http://<gateway>/api/<apikey>/sensors -d '{"name": "test", "modelid": "test", "swversion": "1.6.1", "type": "CLIPOpenClose", "uniqueid": "A7:8E:24:A8:D0:D0-01-1000", "manufacturername": "test"}'`

You will get the ID of the new sensor.

Create the rule to map water to open:

`curl -vv -XPOST http://<gateway>/api/<apikey>/rules -d '{ "actions": [ { "address": "/sensors/<id of clip sensor>/state", "body": { "open": true }, "method": "PUT" } ], "conditions": [ { "address": "/sensors/<id of leak sensor>/state/water", "operator": "eq", "value": true } ] , "name": "Copy water to open" }'`

Create the rule to map water: false to closed:

`curl -vv -XPOST http://<gateway>/api/<apikey>/rules -d '{ "actions": [ { "address": "/sensors/<id of clip sensor>/state", "body": { "open": false }, "method": "PUT" } ], "conditions": [ { "address": "/sensors/<id of leak sensor>/state/water", "operator": "eq", "value": false } ] , "name": "Copy no water to close" }'`

Expose it to homekit:

`ui put /devices/A7:8E:24:A8:D0:D0 '{"expose": true}'`
