### ISSUE TITLE
IKEA Trådfri scene issue

### ISSUE THREAD

**Issue by WeylandYutani82** [ebaauw/homebridge-deconz#232]
Refering to [#171](https://github.com/ebaauw/homebridge-deconz/issues/171) I think I found something with the latest Deconz version: when just setting brightness or just color temperature, all works as expected (also directly within Phoscon (Deconz)). But when adding the light bulb to a scene which adjusts both, color and brightness, the mentioned issue occurs. Would it possible to adjust your plugin, that it waits a second between sending brightness and color if both values are changed at the same time?

**Comment by ebaauw** [comment]
Hom
