### ISSUE TITLE
Sensors and plugs are visible in Homebridge but not in Homekit

### ISSUE THREAD

**Issue by T3CHN3W** [ebaauw/homebridge-deconz#234]
Hello,
A short description of my problem:
I see the sensors and plugs I added via the Phoscon app in Homebridge (v1.8.5, Node-js v22.12.0), but not in Homekit (Homepod mini v18.2 - 22K155).

Is this a known issue with the latest version of Homebridge and a Homepod mini?

Unfortunately I updated my Raspi pi and Docker to the latest version 1 week ago and at the same time updated the Homepod mini to the above version. Now I can't figure out which change could have caused this problem. Before the update, everything worked without any problems.

Before the update I was using the homebridge-hue app, but since the developer of both apps is the same I figured it shouldn't make a difference which app I use. BTW even with the hue app I can see the sensors in the homebridge app but unfortunately not in Homekit.

I see the following warnings or comments in the protocol:

`[12/26/2024, 9:11:40 AM] [deCONZ] warning: recommended version: node v22.11.0`

```
[12/26/2024, 9:11:42 AM] [deCONZ] 1 gateways
[12/26/2024, 9:11:42 AM] [deCONZ] created debug dump file /var/lib/homebridge/homebridge-deconz.json.gz
(node:116406) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ... to show where the warning was created)`
```
I can see other sensors like Timer and Pihole in Homekit as usual.

I wonder if you are facing the same problem.

**Comment by ebaauw** [comment]
If the devices are visible in Homebridge, then the plugins work correctly.  Make sure the (child) bridge(s) is/are paired with HomeKit.  If this fails, or the bridges cannot be reached by HomeKit, the issue is with your home network, most likely the Docker network settings.

**Comment by T3CHN3W** [comment]
Hi ebaauw, thank you very much for your reply. It was actually because I really had to pair the child bridge with Homekit again separately. I didn't have to do that with the older versions of Homebridge, which is why it wasn't on my radar.

For all those who have the same issue:

1. Click on "Plugins" in Homebridge 
2. on the 3-dot symbol of the "Homebridge deCONZ" plugin 
3. Bridge settings 
4. Scan the QR code with the Homeapp -->  Bridge with all devices should now have been added to Homekit
