### ISSUE TITLE
Unreachable device status

### ISSUE THREAD

**Issue by mangoschorle** [ebaauw/homebridge-deconz#236]
Is there a way that allows for unreachable devices to be displayed as "off"?

I have a Hue bulb in a socket that is "classically" switched by a wall switch. The issue I have is that if I switch the bulb off using the wall switch (The bulb is now unreachable) it is still displayed as "On" in my HomeKit.

**Comment by ebaauw** [comment]
Set the `wallSwitch` setting on the accessory, see https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration#settings-2.

Note that I don’t recommend using traditional wall switches for smart lights.  It might take several minutes for deCONZ to realise that the light is no longer reachable.  Also, powering down routers might have a negative impact on the Zigbee network.

**Comment by mangoschorle** [comment]
Got it! I never thought about the (rather obvious) fact that I am disturbing the zigbee mesh by removing and adding routers. Thanks for pointing that out.
