### ISSUE TITLE
[deCONZ] Roomname: warning: assertion failed

### ISSUE THREAD

**Issue by axelweichert** [ebaauw/homebridge-deconz#24]
Hi,

since today i am getting the mesage "[deCONZ] Roomname: warning: assertion failed" in the log. Do you have any suggestions to this message? Wasn`t there before.

**Comment by ebaauw** [comment]
Hm, Homebridge deCONZ cannot compute the colour temperature value for adaptive lighting.  Did you expose the room group and enable adaptive lighting on it?

**Comment by axelweichert** [comment]
Yes, when i disable it, the message is gone. Thanks for your quick help. Great work you have done with new plugin.

**Comment by ebaauw** [comment]
Could you please check if the issue still occurs in v0.0.14?

I'm not sure if enabling adaptive lighting on groups is a good idea.  Maybe I should remove that feature.  There could also something fishy in the current code handing adaptive lighting; I might need to refactor that.
