### ISSUE TITLE
homebridge-hue -> homebridge-deconz

### ISSUE THREAD

**Issue by iantait** [ebaauw/homebridge-deconz#25]
Just thought I'd share my experience of moving to homebridge-deconz from homebridge-hue

I set up a new homebrdge instance on a different machine, installed homebridge-deconz, pressed the 'authenticate app' button in phoscon - all good - I did get the settings not showing up the first time I tried:

![Screenshot_93](https://user-images.githubusercontent.com/9675477/156753682-8b169399-6165-4020-9a9e-2714cab70978.jpg)

In the original homebridge-hue install, I changed the config to false for lights, sensors etc

In eve, I selected the new deconz gateway, and expose, and then expose for the lights and sensors etc.
I then had to move the accessories to the correct rooms.

All seemed ok.  I then installed homebridge-deconz on the original homebridge instance, and removed the temporary homebridge instance from homekit, having to move accessories to their correct rooms again.

I do seem to have an extra 'settings' accessory for every real accessory - haven't figured out how not to have those yet.

Aside from that, bit of a no-brainer.

Thanks again for your work!

**Comment by ebaauw** [comment]
> I do seem to have an extra 'settings' accessory for every real accessory - haven't figured out how not to have those yet.

It's an additional service, not an accessory, see https://github.com/ebaauw/homebridge-deconz/wiki/Gateway-Accessory.  I'm trying to get rid of these, in favour of dynamic configuration through the Homebridge UI.  I have the technical foundation working, including communication between the running plugin and the UI.  Still struggling with the UI part, though.
