### ISSUE TITLE
Switch service is Sensor?

### ISSUE THREAD

**Issue by aryelevin** [ebaauw/homebridge-deconz#28]
I see that Switch service is extended by DeconzService.SensorsResource, is that correct?
Seems like a wrong mixup with Button service.

Thanks

**Comment by ebaauw** [comment]
Yes, that’s correct.

I think you’re confusing deCONZ resources, HomeKit services, Homebridge deCONZ service delegates.  And wired vs wireless switches.

**Comment by aryelevin** [comment]
OK, so, I'll be happy to get familiar with those.
I want to contribute to the development to adopt some features like switch setting per group light accessory for groups of non dimmable lights such as outlets or even the ubisys SxR which in my case being used for a water boiler etc.
I have also some private stuff I'm using for my needs, so it will be very helpful to understand the project structure and terminology.
Thanks a lot for the amazing work!!!
