### ISSUE TITLE
Sensors are exposed as buttons?

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#3]
eg. motion sensors are exposed as buttons to HOME. Is it wanted like that?
also it should splittet into sensors AND switches.
My switches are never exposed to HOME because they are fully configured with deconz.

for my setup, i used the `homebridge-hue` plugin twice for many month in sub bridges (so this is not a big problem for me):
1. only sensors (together with the `homebridge-alexa` plugin and some other..)
2. only lights from deconz are exposed in an sub bridge (Alexa got the lights directly from deconz)

this is mandatory so alexa can control lights even my internet is broken or the alexa homebridge service is broken.. again..

in this case, i replaced my  "light only" `homebridge-hue` bridge with this plugin and its work great. thank you!

**Comment by ebaauw** [comment]
Not yet supported devices are exposed as switches for now.  That will change as Homebridge deCONZ gains more functionality,

**Comment by ebaauw** [comment]
Supported in v0.0.11.
