### ISSUE TITLE
Can we disable Stateless Programmable Switch Service (logs)?

### ISSUE THREAD

**Issue by Hubsi3** [ebaauw/homebridge-deconz#30]
Hello, I just downloaded your new plugin and I am beginning to test it now.
For now everything seems working fine! Great work.

But one little thing is annoying to me: The logs of home bridge are filled with the Stateless Programmable Switch Service: "Button: Programmable Switch Event: Single Press" every minute. Can we disable this or switch off the logs?
So what is the sense for this Service, why is it enabled by default?

Thanks in advance!

**Comment by Einstein2150** [comment]
same here

` [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`

**Comment by ebaauw** [comment]
You can set the log level dynamically per accessory, through the _Log Level_ characteristic in the _Device Settings_ or _Gateway Settings_ service.

**Comment by Einstein2150** [comment]
> Hello, I just downloaded your new plugin and I am beginning to test it now. For now everything seems working fine! Great work.
> 
> But one little thing is annoying to me: The logs of home bridge are filled with the Stateless Programmable Switch Service: "Button: Programmable Switch Event: Single Press" every minute. Can we disable this or switch off the logs? So what is the sense for this Service, why is it enabled by default?
> 
> Thanks in advance!

I checked it in my environment. The button is pressed periodically to the value of the "Heartrate"-configuration. In my config it is 30 seconds so every 30 seconds the "Gateway-button" is pressed...

**Comment by Hubsi3** [comment]
Thanks for your fast reply. As the button is from the Gateway, I have to change the log level in the Gateway settings, haven't I? To which value will I have to set it? It is currently 2. 

@Einstein2150 I don't think that it is related to the Heartrate-config, as it is also 30s for me and the button is triggering every minute.

**Comment by ebaauw** [comment]
It's to enable periodic automations.

Yes, you need to set the level in the _Gateway Settings_.  See https://github.com/ebaauw/homebridge-lib/wiki/Log-Messages for details on the levels.

**Comment by Hubsi3** [comment]
Ok, so I had to change log level to 0 to hide the messages. According to the wiki I should now only not get info messages like device state changes. However I keep getting messages like the state of a contact sensor changed from 0 to 1.
![F112384B-546D-4BCB-8632-8C4810F35FC4](https://user-images.githubusercontent.com/34960772/160006889-66be0cea-63a6-491d-8b8a-2e30420462cf.jpeg)
And of course I want to get those messages, but not the periodic button messages. So is this intended behaviour or am I doing something wrong?

**Comment by Einstein2150** [comment]
> Ok, so I had to change log level to 0 to hide the messages. According to the wiki I should now also don’t get info messages like device state changes. However I keep getting messages like the state of a contact sensor changed from 0 to 1.
> 
> ![F112384B-546D-4BCB-8632-8C4810F35FC4](https://user-images.githubusercontent.com/34960772/160006889-66be0cea-63a6-491d-8b8a-2e30420462cf.jpeg)
> 
> And of course I want to get those messages, but not the periodic button messages. So is this intended behaviour or am I doing something wrong?

You can set the log level to 0 for every device separately. It's your choice. In my case I eliminated my Christmas light debug completely...

**Comment by Hubsi3** [comment]
Ah okay, thanks for clarification! That makes sense now!

**Comment by basti184** [comment]
Hello, 
I read through this thread and the associated link about Log-Messages several times today and tried different things but I can‘t get it working. I am also trying to suppress the log message for the Programmable Button. 
I was successful in adding the log level to HomeKit, changed it to 0 but that did not help. I get stuck after that. I don‘t seem to understand the points in the wiki which come after that. E.g. „ Next, call AccessoryDelegate.manageLogLevel() to re-define logLevel to return the value of the CharacteristicDelegate instead.“ 
Sorry for the dummy question and I hope someone can help. 
Thanks
