### ISSUE TITLE
Where to find ID of the Homebridge deCONZ migration resource link

### ISSUE THREAD

**Issue by Goldsucher** [ebaauw/homebridge-deconz#31]
Hi,

sorry for that question. I searched all Readmes but I could't find an answer.

Where can I find the ID of the migration resource link?

Thanks for help!

**Comment by ebaauw** [comment]
There should be a message in the log, when you change the devices being exposed:
```
[4/1/2022, 10:27:04 AM] [pi5] pi5: migration: /resourcelinks/1: 13 resources
```

**Comment by Goldsucher** [comment]
ok.. I'm not sure if I understand it correctly:

The migration is for exclude specific devises/sensors that they don't shown app in the home app right? 

Because if I switch expose status for the deconz daylight sensor (which I don't need in my home app) with the eve app I don't see a message in the log.

Maybe I didn't get the migration feature at all 😄

thanks for your help!

**Comment by Goldsucher** [comment]
ahh I see. Okay that everything is fine, I've completely switch to Homebridge deCONZ
