### ISSUE TITLE
Cannot obtain an api key

### ISSUE THREAD

**Issue by MrksHfmn** [ebaauw/homebridge-deconz#32]
I'm trying to link deconz with the plugin right now. but i can't tell if it works or not. when i start the api sharing in phoscon, apparently an api key can be obtained. but this is not written in the config. in my old homebridge hue plugin, such a users config was written. Also, no devices (sensors, lights, etc) are published in homebridge (even i share it in config).

**homebride log**:
`Phoscon-GW: warning: 042DC3A196: potentially stale api key: {"create date":"2022-04-04T16:42:23","last use date":"2022-04-04T17:10:03","name":"homebridge-deconz#futro-s940"}`

**homebridge config.yaml**

{
    "bridge": {
        "name": "Homebridge 3CB6",
        "username": "xx:xx:xx:xx:xx",
        "port": 53473,
        "pin": "xx-xx-xx-xx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8088,
            "platform": "config"
        },
        {
            "name": "deCONZ",
            "hosts": [
                "192.168.1.101:2080"
            ],
            "platform": "deCONZ"
        }
    ]
}

**Comment by ebaauw** [comment]
> but this is not written in the config 

No, it’s not.  The API key is stored in `cachedAccessories`. 

> in my old homebridge hue plugin, such a users config was written.

No, for Homebridge Hue you had to edit that file manually.

> Also, no devices (sensors, lights, etc) are published in homebridge (even i share it in config).

See the README: Homebridge deCONZ has no config.json settings.  Use Eve or another HomeKit app to change the configuration from HomeKit.
