### ISSUE TITLE
Any way to re-sync names from deCONZ to HomeKit?

### ISSUE THREAD

**Issue by fullphat** [ebaauw/homebridge-deconz#33]
Great plugin!

Just added some Hue lights and dimmer switches but they appear in HomeKit with the name deCONZ assigns when the device is found rather than what I rename it to in the deCONZ app.

Is there any way to have the plugin sync the current accessory names from deCONZ?

Thanks

**Comment by ebaauw** [comment]
Accessory and service names are maintained over the HomeKit API, inaccessible by the accessories (I.c. Homebridge) themselves.  They’re copied from the accessory when it’s paired to HomeKit, but after that, they can only be changed through a HomeKit app.

You could un-expose and re-expose the accessories, but this will cause you to lose any associations to HomeKit rooms, groups, scenes, and automations.

**Comment by fullphat** [comment]
Thanks!  That works for me.  Add > rename > un-expose > re-expose > add to scenes.  Will try that. 👍🏼
