### ISSUE TITLE
homebridge-deconz spamming logfile

### ISSUE THREAD

**Issue by alaindesigns** [ebaauw/homebridge-deconz#34]
Hey,

the deconz plugin is spamming my log file every minute. Here is a snippet of it but it goes on much longer, since it pushes the message every minute with no breaks:

`[09/04/2022, 11:59:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:00:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:01:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:02:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:02:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Double Press`
`[09/04/2022, 12:03:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:04:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:05:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:06:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:07:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`
`[09/04/2022, 12:08:35] [deCONZ] Phoscon-GW Button: Programmable Switch Event: Single Press`

Hope someone can clarify why this is happening and how to stop it.

**Comment by ebaauw** [comment]
See #30
