### ISSUE TITLE
Light Groups which are not dimmable showing as dimmable

### ISSUE THREAD

**Issue by keness521** [ebaauw/homebridge-deconz#37]
Apologies if this isn't the right place to inquire about this. I have a suspicion that this is something Phoscon should be in charge of, because I assume the plugin just passes the info provided to it along to HomeKit.

In Phoscon, I've created a Group of 12 lights which are all identical and are simple on-off mains wall switches. (Wall switches exposed as lights.)

I've never used Groups before and it was great. I put the light switch for every room in the basement into the Group, and I can turn off the entire basement with one tap. But I still have all the individual rooms available as well. Previously, I made a scene for all the light switches, and it did the same thing, but was a scene rather than a "device" and the lights all flicked off in a random cascading pattern. It was kind of futuristically cool, actually, but I still prefer the Group method because it comes through as a device of its own, and the lights all operate in perfect unison.

The issue is that the Group device comes through as a dimmable light, rather than just an on-off light. Those same switches would expose as a simple on-off light if they were on their own.

Originally it was coming through as an Adaptive Lighting "light" but I did turn that off. But I can't figure out how to make it just on-off rather than dimmable. Currently, it shows as "100%" (rather than ON) when its on, and OFF when off.

If this is just because that is how Phoscon makes the Group and there is no real way around it, no worries, at least I'll know and I can stop looking for a solution. hah

**Comment by ebaauw** [comment]
Indeed, the deCONZ API exposes groups with dimming and colour capabilities, irrespective of what capabilities the lights have.  Once I will have configuration of accessories figured out for Homebridge deCONZ, you will be able to expose the group as _Outlet_ or _Switch_, rather than as _Lightbulb_, so it won't show as dimmable in HomeKit.  Until then, you'll have to use Homebridge Hue with an `outlet` or `switch` resource link.

**Comment by keness521** [comment]
Perfect, exactly what I needed to know. 

You've dropped a couple of hints about an interface that you're working on, and I see some preliminary mentions of it in the startup log. I'm very excited to see what you've been working on.

I know user interfaces aren't your favorite thing, so your efforts are very much appreciated!
