### ISSUE TITLE
Expose devices as fans, switches etc

### ISSUE THREAD

**Issue by Grant-murphy1** [ebaauw/homebridge-deconz#4]
Good Afternoon, is it possible to expose the devices from Deconz in Homekitas fans and switches, rather than lights?

**Comment by ebaauw** [comment]
Not yet, but I plan to make that configurable through the _Device Settings_ service.

**Comment by aryelevin** [comment]
Oh, perfect.
This is the only obstacle for me to use it.
At this time I have groups of outlets which I want to get it as Switch type in HomeKit.
With my current homebridge-hue plugin configuration I can do this, but now its impossible, thus I'm in the middle with proceeding with the migration and I cannot get any further without it.
Any updates on this implementation?

Thanks a lot!
