### ISSUE TITLE
nothing is exposed to HomeBridge/Homekit

### ISSUE THREAD

**Issue by romanbalsiger** [ebaauw/homebridge-deconz#41]
After initial setup absolutely no devices (lights/sensors/switches/groups) are exposed to homebridge or homekit. do i miss any necessary config?

`{
            "name": "ZigBee_newer",
            "hosts": [
                "10.10.11.2"
            ],
            "platform": "deCONZ",
            "_bridge": {
                "username": "0E:64:43:39:03:B9",
                "port": 34214
            }
        }`

**Comment by Automayted** [comment]
I too was a little confused after installing the new deCONZ plugin and had to re-read Erik's documentation. Hopefully I can help.

Re-read the whole [Configuration](https://github.com/ebaauw/homebridge-deconz#Configuration) section first.

_"**Set Expose on the Gateway Settings service of the gateway accessory** to retry obtaining an API key. Homebridge deCONZ will not retry to obtain an API key on Homebridge restart."_

After you allowed the new Homebridge plugin to authenticate to the Conbee, you need to use Eve or the Home+ app to edit the expose settings of the Conbee device (button device in HomeKit). Once you expose your lights, sensors, or groups, you'll see the devices added to HomeKit. This change to "dynamic" from the old method is the reason this process is so different with the new deCONZ plugin. The dynamic method eliminates the need to restart the Homebridge plugin for devices to update in HomeKit.

**Comment by romanbalsiger** [comment]
> Hopefully I can help.

Yes you did! thanks a lot!

**Comment by blue-kaleidoscope** [comment]
> After you allowed the new Homebridge plugin to authenticate to the Conbee, you need to use Eve or the Home+ app to edit the expose settings of the Conbee device (button device in HomeKit). Once you expose your lights, sensors, or groups, you'll see the devices added to HomeKit.

Could you please explain how this is exactly done in Eve?
When I click on the device I see the following settings but I have no idea how to expose lights:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/56046815/185798115-a998527a-4e41-445e-8b59-d81f85ca6b45.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/56046815/185798164-7ebb1d9a-ec23-4b55-92da-63dd3356b7d8.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/56046815/185798177-9265d02f-3a5c-4984-9d83-235081b80524.png">
