### ISSUE TITLE
Cannot expose a group without also exposing all scenes from the group

### ISSUE THREAD

**Issue by Automayted** [ebaauw/homebridge-deconz#42]
I'm able to expose all groups, and then hide the individual groups that I do not want exposed in HomeKit. However, when I expose groups that contain scenes, I also see that all scenes in that group are exposed as switches. When I uncheck expose on the unwanted individual scene switches from an exposed group, the whole group is then also removed from HomeKit.

My use case is multiple Hue Downlights that I'd like to expose as a single bulb to HomeKit. They are grouped in deCONZ, but also have scenes associated. I've hidden (un-exposed) the individual bulbs, but can't expose the group without also exposing the scenes, which is not what I want.

Any workaround for this?

**Comment by ebaauw** [comment]
I’m still figuring out how best to expose more detailed dynamic settings in Homebridge deCONZ.  Currently, the only way to get this done is to use Homebridge Hue instead.

**Comment by ebaauw** [comment]
In v0.1.0.

**Comment by sadpixel** [comment]
Thanks so much for adding this feature. It is very useful to now have this option per-group!
