### ISSUE TITLE
Enhancement: dew point characteristic for temperature/humidity sensors?

### ISSUE THREAD

**Issue by crazykiwi2003** [ebaauw/homebridge-deconz#48]
Hello again,

For me it would be a great benefit to have an additional characteristic „dew point“ for all temperature/humidity sensors, which must be calculated from temperature and humidity (e.g. for deciding whether it makes sense to open windows to get rid of humidity).

Not sure whether that can be done within the plugin - before I did that via FHEM, but I am trying avoid FHEM.

Would that be possible?

Best regards
Thomas

**Comment by ebaauw** [comment]
In my view, a Homebridge plugin exposes devices to HomeKit, nothing more, nothing less.  Happy to expose dew point (as I've done in Homebridge WS), where the sensor and/or deCONZ provide this, but I won't be computing new attributes in the plugin.

Technically, it might be challenging to do this in deCONZ, as you'd need input from two different Zigbee clusters.

**Comment by crazykiwi2003** [comment]
Alright, I totally understand. Anyway many thanks for your great work
