### ISSUE TITLE
deconz cli node missing

### ISSUE THREAD

**Issue by RobMcRob24** [ebaauw/homebridge-deconz#52]
Hi,

I can't start the deconz cli anymore. I get the following error message:
root@homebridge:/homebridge# deconz
/homebridge/node_modules/.bin/deconz: 16: exec: node: not found

I'm running homebridge-deconz plugin in a docker container (oznu/homebridge) in the latest version from this week on a Synology NAS

I can't tell you, if this comes up due to the newest version of your plugin or from the last version of the docker container and their changes.

If you need further informations or some debug messages, please come back to me.

Thanks,
Roland

**Comment by ebaauw** [comment]
I think the message indicates that NodeJS cannot be found.  That would be an issue with the NodeJS installation in the container, nothing to do with the plugin.  You might try and start `node` from the command line in the container, and check the output of `/usr/bin/env node`.  I think it might be moved to a different directory with the new Homebridge package.  I don’t run Docker and cannot help there.

**Comment by RobMcRob24** [comment]
OK, I've changed the PATH variable in the container and it works again. Thanks for your hint!
