### ISSUE TITLE
Warning: when installed on an Apple iMac (El Capitan 10.11)

### ISSUE THREAD

**Issue by ghdbwise** [ebaauw/homebridge-deconz#53]
[6/19/2022, 1:51:46 PM] [deCONZ] warning: TypeError: Cannot read properties of null (reading '1')
    at SystemInfo.getMacInfo (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/SystemInfo.js:298:14)
    at SystemInfo.init (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/SystemInfo.js:190:25)
    at DeconzPlatform._main (/usr/local/lib/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/Platform.js:185:5)

**Comment by ebaauw** [comment]
That's a bug alright, but it shouldn't impact the functionality of the plugin.

I'm trying to get the friendly system name (like _Mac mini Server (Mid 2011)_), but Apple seems to have many ways of hiding this.  Could you please list the output of
```
plutil -p ~/Library/Preferences/com.apple.SystemProfiler.plist
```
and of
```
system_profiler SPHardwareDataType
```

**Comment by ghdbwise** [comment]
Hi Eric,
here are the requested informations:
=================================================================
SystemProfiler.plist:
{
  "OS Names" => {
    "15G18013-de_DE" => "OS X El Capitan"
    "15G1212-de_DE" => "OS X El Capitan"
    "14A389-de_DE" => "OS X Yosemite"
    "15B42-de_DE" => "OS X El Capitan"
    "15G21013-de_DE" => "OS X El Capitan"
    "15G17023-de_DE" => "OS X El Capitan"
    "14E46-de_DE" => "OS X Yosemite"
    "15G1421-de_DE" => "OS X El Capitan"
    "15C50-de_DE" => "OS X El Capitan"
    "15D21-de_DE" => "OS X El Capitan"
    "14B25-de_DE" => "OS X Yosemite"
    "15G1611-de_DE" => "OS X El Capitan"
    "15G22010-de_DE" => "OS X El Capitan"
    "15E65-de_DE" => "OS X El Capitan"
    "15G1004-de_DE" => "OS X El Capitan"
    "14D136-de_DE" => "OS X Yosemite"
    "15G1217-de_DE" => "OS X El Capitan"
    "15G1510-de_DE" => "OS X El Capitan"
    "14C109-de_DE" => "OS X Yosemite"
    "15G1108-de_DE" => "OS X El Capitan"
    "15G31-de_DE" => "OS X El Capitan"
  }
  "NSTableView Sort Ordering Contents" => [
  ]
  "CPU Names" => {
    "9G8-de_DE" => "Mac mini (Ende 2009)"
    "0TJ-de_DE" => "iMac (24 Zoll, Anfang 2009)"
  }
  "NSTableView Hidden Columns Contents" => [
  ]
  "NSWindow Frame SystemProfile" => "390 100 1046 1062 0 0 1920 1177 "
  "NSTableView Columns Contents" => [
    0 => <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 08636f6e 74656e74 7386>
    1 => "165"
  ]
}
=================================================================
SPHardwareDataType:
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac9,1
      Processor Name: Intel Core 2 Duo
      Processor Speed: 2,66 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache: 6 MB
      Memory: 8 GB
      Bus Speed: 1,07 GHz
      Boot ROM Version: IM91.008D.B08
      SMC Version (system): 1.45f0
      Serial Number (system): VM937ETS0TJ
      Hardware UUID: 50D12301-37DD-5248-8046-7163B08E556A

=================================================================
You are right, everything is running fine. Only a warning.
You are doing a great work. I already use homebridge-deconz in my productive environment.
Regards from germany.
Peter

**Comment by ghdbwise** [comment]
After patching the SystemInfo.js the warning is gone.

Instead comes the following correct message: 

[6/19/2022, 6:53:30 PM] [deCONZ] hardware: iMac
[6/19/2022, 6:53:30 PM] [deCONZ] os: Mac OS X El Capitan 10.11.6 (15G22010)

**Comment by ebaauw** [comment]
Thanks.  I take it, this is the 24" iMac, _iMac (24 Zoll, Anfang 2009)_?

Somehow they only use the last three characters from the serial number, instead of the last four.  This commit should handle that.
