### ISSUE TITLE
"Phoscon-Gateway Button: Programmable Switch Event: Single Press" every minute?

### ISSUE THREAD

**Issue by eytschjey** [ebaauw/homebridge-deconz#57]
I'm on homebridge-deconz v0.0.17 on Homebridge v1.5.0 on a Windows 11 PC. It's a new install, so there's no other plugins installed.

homebridge-deconz starts up fine and i can control all my devices from the WEB UI in Homebridge and the Home App, but my homebridge log shows "Phoscon-Gateway Button: Programmable Switch Event: Single Press" every minute. 

I've manually added the Gateway IP in the plugin settings, and added the information from the log file that it said to add to config.json, so it looks like this now:

"platforms": [
        {
            "platform": "Hue",
            "users": {
                "001788FFFExxxxxx": "ZhTr82KJ5to2lwQgk7DUAXOVWsaX-xxxxxxxxxx-F"
            }
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "deCONZ",
            "hosts": [
                "192.168.12.30"
            ],
            "platform": "deCONZ"
        }
    ],

I'm not sure if this is a "problem", as I'm new to a lot of this stuff, but I would be happy to know what I can do to stop this behavior. Thanks a lot in advance!

**Comment by ebaauw** [comment]
See closed issue
