### ISSUE TITLE
Display opposite state of shutter in HomeKit 

### ISSUE THREAD

**Issue by sirinveen** [ebaauw/homebridge-deconz#58]
I install your plugin but for shutter in HomeKit the final state is opposite.

Your plugin receive the good information from deconz (see below):

`[
  {"/": {"etag": "f367e151438703a2bfbb5e67af23259c", "hascolor": false, "lastannounced": null, "lastseen": "2022-07-24T14:34Z", "manufacturername": "_TZ3000_dbpmpco1", "modelid": "TS130F", "name": "Volet Cuisine", "state": {"bri": 0, "lift": 100, "on": false, "open": true, "reachable": true}, "swversion": null, "type": "Window covering device", "uniqueid": "a4:c1:38:d1:0b:18:d2:ce-01"}},
  {"/etag": "f367e151438703a2bfbb5e67af23259c"},
  {"/hascolor": false},
  {"/lastannounced": null},
  {"/lastseen": "2022-07-24T14:34Z"},
  {"/manufacturername": "_TZ3000_dbpmpco1"},
  {"/modelid": "TS130F"},
  {"/name": "Volet Cuisine"},
  {"/state": {"bri": 0, "lift": 100, "on": false, "open": true, "reachable": true}},
  {"/state/bri": 0},
  {"/state/lift": 100},
  {"/state/on": false},
  {"/state/open": true},
  {"/state/reachable": true},
  {"/swversion": null},
  {"/type": "Window covering device"},
  {"/uniqueid": "a4:c1:38:d1:0b:18:d2:ce-01"}
]`

Lift is 100 means shutter is totally open that it's correct but in HomeKit interface he show me the inverse the shutter is closed.

<img width="115" alt="image" src="https://user-images.githubusercontent.com/102876220/180652228-d89648ad-0b9a-49d0-b17c-6dfaccb4ee6b.png">

I can modify in deconz with DDF but it's not a good solution because animation is not anymore correct in HomeKit display.

Have you a idea to resolve this HomeKit display?

Thanks in advance for your effort!

**Comment by ebaauw** [comment]
Yes, HomeKit uses percentage open, where Zigbee uses percentage closed.  So `state.lift` of 100 means closed, which is mapped to 0% open in HomeKit.

> Your plugin receive the good information from deconz (see below):

No it doesn’t, `open` should be `false` when `lift` is `100`.

> Lift is 100 means shutter is totally open

No, it doesn’t.

**Comment by sirinveen** [comment]
ok understood I can fix this with DDF by deconz and you will receive by the api with open with false. 

Now your API receive the good information for HomeKit what I don't understand when I click on the button in HomeKit to open the shutter he stay with the status "opening" for some minutes without moving the shutter and at final stay with state "closed" :/

Here the process:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/102876220/180659819-37119210-9332-4743-aae4-32e94a688b52.png">


if I click two time (HomeKit shutter button) with a laps of second the shutter is moving for opening but I can see HomeKit "closed" and when it's finish final status "open". Final status is ok but transition is not good. And also is not a solution to click 2 times.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/102876220/180660025-22a98dc0-6869-4929-918d-d9eadbe7ba06.png">

Have you a idea to resolve this issue?

**Comment by ebaauw** [comment]
That’s a tricky one.  HomeKit uses _Target Position_ vs _Current Position_, but the REST API only exposes a single `state.lift`.  When setting `state.lift`, the API initially reports the set value, but as attribute reports come in from the controller, this is updated with the actual position.  Apple’s Home app shows _Opening_ while the _Current Position_ hasn’t reached the _Target Position_, so Homebridge deCONZ ignores any update of `state.lift` right after setting the state.  As a safety net, Homebridge deCONZ updates the target position with the current position after two minutes.

This scheme works well for the controllers I have: the IKEA FYRTUR, the original `lumi.curtain` and the Aqara E1 roller blind controller, that all support attribute reporting of _Current Position Lift Percentage_.

I think in your first try, the controller doesn’t receive the command to change the position, so it shows _Opening_ until the safety net kicks in, and it again shows _Closed_.

I think in your second try, the controller does receive the command, but it looks like the REST API plugin doesn’t receive any attribute reports (I don’t even know if your device is capable of sending these, but if it is, best double check that reporting is configured correctly).  I need to see a debug log file to understand exactly what’s happening here.  It could also be that the controller does send reports, but they don’t reach deCONZ.  I’m a bit suspicious the the command doesn’t reach the controller on the first try.  It might be prudent to check the deCONZ log for interference errors, or use a Zigbee sniffer to check for routing issues.
