### ISSUE TITLE
Owon Multi Sensor Humidity data are not record by Eve App

### ISSUE THREAD

**Issue by sirinveen** [ebaauw/homebridge-deconz#59]
Hi,

Before with your homebridge-hue Eve App record only motion for this sensor.  

Now with this new plugin homebridge-deconz motion, temperature and lux are recorded only humidity is not ... 

For your info I also receive this info when I restart Homebridge perhaps that can help you:

`[homebridge-deconz] This plugin generated a warning from the characteristic 'Resource': characteristic was supplied illegal value: string '/sensors/361, /sensors/362, /sensors/363, /sensors/364, /sensors/365' exceeded max length of 64. See https://homebridge.io/w/JtMGR for more info.`

Here result from your deconz api for humidity sensor '363':

`[
  {"/": {"config": {"offset": 0, "on": true, "reachable": true}, "etag": "ec1c983145924cece8dde9e3765979de", "lastannounced": null, "lastseen": "2022-07-24T14:54Z", "manufacturername": "OWON", "modelid": "PIR313", "name": "Multi Sensor SDB", "state": {"humidity": 4984, "lastupdated": "2022-07-24T14:55:01.915"}, "swversion": "20211221", "type": "ZHAHumidity", "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0405"}},
  {"/config": {"offset": 0, "on": true, "reachable": true}},
  {"/config/offset": 0},
  {"/config/on": true},
  {"/config/reachable": true},
  {"/etag": "ec1c983145924cece8dde9e3765979de"},
  {"/lastannounced": null},
  {"/lastseen": "2022-07-24T14:54Z"},
  {"/manufacturername": "OWON"},
  {"/modelid": "PIR313"},
  {"/name": "Multi Sensor SDB"},
  {"/state": {"humidity": 4984, "lastupdated": "2022-07-24T14:55:01.915"}},
  {"/state/humidity": 4984},
  {"/state/lastupdated": "2022-07-24T14:55:01.915"},
  {"/swversion": "20211221"},
  {"/type": "ZHAHumidity"},
  {"/uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0405"}
]
` 

Thanks in advance for our help and effort!

**Comment by ebaauw** [comment]
> [homebridge-deconz] This plugin generated a warning from the characteristic 'Resource': characteristic was supplied illegal value: string '/sensors/361, /sensors/362, /sensors/363, /sensors/364, /sensors/365' exceeded max length of 64. See https://homebridge.io/w/JtMGR for more info.

So this device is exposed using five `sensors` resources; I think that's a record.  Could you please attach the debug dump file, so I can seen what it looks like?

I'm using my own implementation of Eve history for Homebridge deCONZ, enabling me to create combined history for multiple characteristics, beyond what `fakegato` and standard Eve devices support.  I did create a combined motion. light level, and temperature history for the Hue motion sensor, but I don't have yet a combined motion, light level, temperature, humidity history.  What's the fifth sensor, battery?  Does that already show correctly in HomeKit?

**Comment by sirinveen** [comment]
> What's the fifth sensor, battery? 

Yes

> Does that already show correctly in HomeKit?

Yes here little screenshot of the sensor

<img width="248" alt="image" src="https://user-images.githubusercontent.com/102876220/180660552-4639f1de-754a-435b-be4a-728b5cd0ee66.png">


Here the dump files of this sensor:

`"361":{"config":{"duration":0,"on":true,"reachable":true},"etag":"b3e9382f120a3a42bd22456a71b4f6c6","lastannounced":null,"lastseen":"2022-07-24T18:27Z","manufacturername":"OWON","modelid":"PIR313","name":"Multi Sensor SDB","state":{"lastupdated":"2022-07-24T18:27:28.822","presence":false},"swversion":"20211221","type":"ZHAPresence","uniqueid":"3c:6a:2c:ff:fe:d1:b1:73-01-0500"},"362":{"config":{"offset":0,"on":true,"reachable":true},"etag":"733c4e635da600dd37e845c0f72f58d6","lastannounced":null,"lastseen":"2022-07-24T18:27Z","manufacturername":"OWON","modelid":"PIR313","name":"Multi Sensor SDB","state":{"lastupdated":"2022-07-24T18:23:34.295","temperature":3162},"swversion":"20211221","type":"ZHATemperature","uniqueid":"3c:6a:2c:ff:fe:d1:b1:73-01-0402"},"363":{"config":{"offset":0,"on":true,"reachable":true},"etag":"16414a38891bf6000515758c8032b7ae","lastannounced":null,"lastseen":"2022-07-24T18:27Z","manufacturername":"OWON","modelid":"PIR313","name":"Multi Sensor SDB","state":{"humidity":5130,"lastupdated":"2022-07-24T18:27:23.730"},"swversion":"20211221","type":"ZHAHumidity","uniqueid":"3c:6a:2c:ff:fe:d1:b1:73-01-0405"},"364":{"config":{"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000},"etag":"c84ddbbdbcfe84d3b533d35dbdb90d92","lastannounced":null,"lastseen":"2022-07-24T18:27Z","manufacturername":"OWON","modelid":"PIR313","name":"Multi Sensor SDB","state":{"dark":false,"daylight":false,"lastupdated":"2022-07-24T18:27:27.708","lightlevel":6021,"lux":0},"swversion":"20211221","type":"ZHALightLevel","uniqueid":"3c:6a:2c:ff:fe:d1:b1:73-02-0400"},"365":{"config":{"on":true,"reachable":true},"etag":"16414a38891bf6000515758c8032b7ae","lastannounced":null,"lastseen":"2022-07-24T18:27Z","manufacturername":"OWON","modelid":"PIR313","name":"Multi Sensor SDB","state":{"battery":100,"lastupdated":"2022-07-24T18:19:55.053"},"swversion":"20211221","type":"ZHABattery","uniqueid":"3c:6a:2c:ff:fe:d1:b1:73-01-0001"}`

**Comment by ebaauw** [comment]
Thanks.

> Does that already show correctly in HomeKit?

Sorry, I meant: does the battery already show correctly in HomeKit?

Formatted for legibitily:
```
{
  "361": {
    "config": {
      "duration": 0,
      "on": true,
      "reachable": true
    },
    "etag": "b3e9382f120a3a42bd22456a71b4f6c6",
    "lastannounced": null,
    "lastseen": "2022-07-24T18:27Z",
    "manufacturername": "OWON",
    "modelid": "PIR313",
    "name": "Multi Sensor SDB",
    "state": {
      "lastupdated": "2022-07-24T18:27:28.822",
      "presence": false
    },
    "swversion": "20211221",
    "type": "ZHAPresence",
    "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0500"
  },
  "362": {
    "config": {
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "etag": "733c4e635da600dd37e845c0f72f58d6",
    "lastannounced": null,
    "lastseen": "2022-07-24T18:27Z",
    "manufacturername": "OWON",
    "modelid": "PIR313",
    "name": "Multi Sensor SDB",
    "state": {
      "lastupdated": "2022-07-24T18:23:34.295",
      "temperature": 3162
    },
    "swversion": "20211221",
    "type": "ZHATemperature",
    "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0402"
  },
  "363": {
    "config": {
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "etag": "16414a38891bf6000515758c8032b7ae",
    "lastannounced": null,
    "lastseen": "2022-07-24T18:27Z",
    "manufacturername": "OWON",
    "modelid": "PIR313",
    "name": "Multi Sensor SDB",
    "state": {
      "humidity": 5130,
      "lastupdated": "2022-07-24T18:27:23.730"
    },
    "swversion": "20211221",
    "type": "ZHAHumidity",
    "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0405"
  },
  "364": {
    "config": {
      "on": true,
      "reachable": true,
      "tholddark": 12000,
      "tholdoffset": 7000
    },
    "etag": "c84ddbbdbcfe84d3b533d35dbdb90d92",
    "lastannounced": null,
    "lastseen": "2022-07-24T18:27Z",
    "manufacturername": "OWON",
    "modelid": "PIR313",
    "name": "Multi Sensor SDB",
    "state": {
      "dark": false,
      "daylight": false,
      "lastupdated": "2022-07-24T18:27:27.708",
      "lightlevel": 6021,
      "lux": 0
    },
    "swversion": "20211221",
    "type": "ZHALightLevel",
    "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-02-0400"
  },
  "365": {
    "config": {
      "on": true,
      "reachable": true
    },
    "etag": "16414a38891bf6000515758c8032b7ae",
    "lastannounced": null,
    "lastseen": "2022-07-24T18:27Z",
    "manufacturername": "OWON",
    "modelid": "PIR313",
    "name": "Multi Sensor SDB",
    "state": {
      "battery": 100,
      "lastupdated": "2022-07-24T18:19:55.053"
    },
    "swversion": "20211221",
    "type": "ZHABattery",
    "uniqueid": "3c:6a:2c:ff:fe:d1:b1:73-01-0001"
  }
}
```

**Comment by ebaauw** [comment]
I think it's this one: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5929?

It doesn't seem to be exposed correctly.  The temperature and humidity sensors are on endpoint 3, according to the screenshots, but the API places them under endpoint 1, looking at the `uniqueid`.

**Comment by sirinveen** [comment]
> Does that already show correctly in HomeKit?

yes I can see by Eve App that the battery is 100%. All sensors work correctly and updated periodically. 

> It doesn't seem to be exposed correctly. The temperature and humidity sensors are on endpoint 3, according to the screenshots, but the API places them under endpoint 1, looking at the uniqueid.

Good catch! I don't see that.

But why temperature now working in Eve App despite the endpoint is not correct and humidity not?!?

And how can I resolve that? It look like deconz don't give the correct endpoint :/ I imagine I must open a support by deconz...

**Comment by ebaauw** [comment]
> And how can I resolve that?

I think you're using an old DDF file.

> But why temperature now working in Eve App despite the endpoint is not correct and humidity not?!?

Because Homebridge deCONZ doesn't expose history for humidity, see above.

**Comment by sirinveen** [comment]
> I think you're using an old DDF file.

Nope I use my own DDF who works perfectly just don't see that endpoint in deconz was not correct in API

> Because Homebridge deCONZ doesn't expose history for humidity, see above.

Really?!? because I have a Aqara Humidity Sensor and I can see in realtime humidity into Eve App

**Comment by ebaauw** [comment]
Should work in v0.1.0, but I cannot test it, as I don't have this device.

**Comment by sirinveen** [comment]
Confirm with the new release 0.1.3 is working now. Thanks.
