### ISSUE TITLE
Display newline despite with option -n

### ISSUE THREAD

**Issue by sirinveen** [ebaauw/homebridge-deconz#61]
Hi,

When I use your cmd deconz with option -n i can see 2 lines in a editor.

deconz -H 192.168.1.1:80 -K 123456 get -n /lights/40/state/lift > file

![image](https://user-images.githubusercontent.com/102876220/181183616-1b42e4a7-0cdd-4820-8673-bda11756ca00.png)

Can you fix this?

**Comment by ebaauw** [comment]
No, that's a feature of your editor.  `deconz get -n ...` outputs only a single line, terminated by a newline.
