### ISSUE TITLE
Support smoke detectors 

### ISSUE THREAD

**Issue by albinmedoc** [ebaauw/homebridge-deconz#64]
Any plans to support smoke detectors?

**Comment by ebaauw** [comment]
No, they should already be supported.  Which model isn’t working?

**Comment by albinmedoc** [comment]
Only an outlet was shown triggering the siren. But after I rebooted the server the smoke detector was also available. 

Everything works fine now.

**Comment by albinmedoc** [comment]
Only an outlet was shown triggering the siren. But after I rebooted the server the smoke detector was also available.

Everything works fine now.
