### ISSUE TITLE
homebridge-deconz is connected to the Deconz server but see only dummy switch

### ISSUE THREAD

**Issue by JustAnotherPU** [ebaauw/homebridge-deconz#65]
Hello,

I am new to using this plugin, but I can't seem to expose any of my lights and sensors in homebridge, I can see that the plugin connects successfully to the Deconz server but see and expose only a dummy switch no lights or sensors.

I am missing something here? 

Thank you for your help

**Comment by ebaauw** [comment]
See the README: set _Expose Lights_ in the _Gateway Settings_ service in Eve.
