### ISSUE TITLE
Adaptive lightning

### ISSUE THREAD

**Issue by ursusHU** [ebaauw/homebridge-deconz#67]
In the predecessor Hue plugin it was possible to modify the default warmth (?) of the lights. This way in the evening I really had "orange" coloured lights automatically, and during the day white light. It really worked perfectly. In the homebridge-deconz plugin I couldn't find such possibility, so I have white lights also at night. (eg. instead of 430 mired 323 mired @22:00) Is there any way to modify this? Thanks in advance.

**Comment by ebaauw** [comment]
Not yet.

**Comment by ursusHU** [comment]
Thank you! Any idea when this feature can be expected? 
For me the global setting was perfect, currently I can’t think of any use case where I would use different settings for each light, but I have ikea bulbs everywhere.

**Comment by torandreroland** [comment]
@ebaauw: Should there be a _"brightnessAdjustment",_ around [here](https://github.com/ebaauw/homebridge-deconz/blob/18af593e6f510dfdbe4227e95796673768cbe3fb/config.schema.json#L104)?

**Comment by torandreroland** [comment]
@ebaauw: I'm getting constant "assertion failed" in the logs now for lights that are not supporting adapting lightning when they are on. Could it be because [initAdaptiveLighting is called for state updates](https://github.com/ebaauw/homebridge-deconz/blob/17431f193bf8159fe55c67e84a56bea3fd792090/lib/DeconzService/Light.js#L324)?

**Comment by ebaauw** [comment]
> Should there be a "brightnessAdjustment", around [here](https://github.com/ebaauw/homebridge-deconz/blob/18af593e6f510dfdbe4227e95796673768cbe3fb/config.schema.json#L104)?

Yes, my bad.

> I'm getting constant "assertion failed" in the logs now for lights that are not supporting adapting lightning when they are on.

Do you mean for lights that don’t carry _Color Temperature_?

> Could it be because [initAdaptiveLighting is called for state updates](https://github.com/ebaauw/homebridge-deconz/blob/17431f193bf8159fe55c67e84a56bea3fd792090/lib/DeconzService/Light.js#L324)?

Oops, the should be a check that adaptive lighting is supported, before creating the adaptive lighting handler.

**Comment by torandreroland** [comment]
Yes, they don’t support color temperature.

**Comment by ebaauw** [comment]
Could you try beta v0.0.22-0?  I'm sorry, I don't have a setup ready with a light without colour temperature support to test this myself.

**Comment by ebaauw** [comment]
Published v0.0.22.
