### ISSUE TITLE
Plugins: Homebridge Hue vs. Homebridge deCONZ

### ISSUE THREAD

**Issue by aschmidt74** [ebaauw/homebridge-deconz#70]
I struggle with some fundamental issue here.
All devices visible when running the `hue` plugin are **lost** when the `deCONZ` plugin is enabled (hue disabled).

HomeBridge log reads:
```
[8/19/2022, 5:05:43 PM] Loaded plugin: homebridge-deconz@0.0.21
[8/19/2022, 5:05:43 PM] Registering platform 'homebridge-deconz.deCONZ'
[8/19/2022, 5:05:46 PM] [deCONZ] Initializing deCONZ platform...
[8/19/2022, 5:05:46 PM] [deCONZ] homebridge-deconz v0.0.21, node v16.17.0, homebridge v1.5.0, homebridge-lib v5.6.5
[8/19/2022, 5:05:46 PM] [deCONZ] Phoscon-GW: dresden elektronik deCONZ / ConBee II gateway v2.17.1
[8/19/2022, 5:05:46 PM] [deCONZ] hardware: x64
[8/19/2022, 5:05:46 PM] [deCONZ] os: Ubuntu 20.04.4 LTS
[8/19/2022, 5:05:46 PM] [deCONZ] restored 1 accessories from cache
[8/19/2022, 5:05:46 PM] [deCONZ] ui server: listening on http://127.0.0.1:42468/
[8/19/2022, 5:05:48 PM] [deCONZ] Phoscon-GW: websocket connected to ws://192.168.0.22:443
[8/19/2022, 5:05:48 PM] [deCONZ] 1 gateways
[8/19/2022, 5:05:48 PM] [deCONZ] created debug dump file /var/lib/homebridge/homebridge-deconz.json.gz
```
the .json file is 85kB in size and aparently lists all properties of all zigbee devices in question.

**Comment by aschmidt74** [comment]
I cleared the cache: `Phoscon-GW (homebridge-deconz)`
and removed all API-keys from the gateway.

but now I cant even get a new API key, only this:
```
[8/19/2022, 5:50:45 PM] [deCONZ] Phoscon-GW: warning: unlock gateway and set Expose to obtain an API key`
```
of course the 'button' is pressed.

`netstat` on the gateway shows this:
```
tcp        0      0 0.0.0.0:81              0.0.0.0:*               LISTEN      458/deCONZ
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      458/deCONZ
```

so the plugins Gateway should be `<gatewaysIP>:81`, right?!
`"forceHttp": true` is in effect too.

**Comment by ebaauw** [comment]
In Eve, or another decent HomeKit app, set _Expose Lights_ in the _Gateway Settings_ service, see README.

**Comment by aschmidt74** [comment]
thanks for the fast response, and I re-red the readme, and did a search for the terms, however;
my eve app (on iPhone) has no _Gateway Settings_ or _Services_!

So **where xactly** needs the _Expose Lights_ to be set?
Is it a switch?
is it a named group?

This seems essentially important but I'm missing this important hint or snapshot in the readme.

**Comment by ebaauw** [comment]
That screenshot is from a gateway accessory exposed by Homebridge Hue, not by Homebridge deCONZ.

**Comment by aschmidt74** [comment]
You see, I am just guessing in the dark; There was no trace of `hue` or `homebridge-hue` running in my system - but maybe homekit is a little slow to get my change of plugins.

**regardless; where can I** `set Expose Lights in the Gateway Settings service` **?!**
please can you give me a hint to that...

**Comment by ebaauw** [comment]
Same place as above screenshot, but then for the accessory exposed by Homebridge deCONZ.

Are you running Homebridge deCONZ in a child bridge, or a separate (new) Homebridge instance?  If so, did you pair it to HomeKit?

**Comment by aschmidt74** [comment]
I did not chosoe the child-bridge option, nor is there another HB instance.
all mentioned above happens in the one and main HB instance.

**Comment by ebaauw** [comment]
I’m not sure you can run Homebridge Hue and Homebridge deCONZ in one Homebridge instance and have both expose the same gateway.  Both would use the same UUID for the gateway accessory, generated from the `bridgeid`.  Do you see two gateway accessories in Eve’s _Accessories_ view (under the _Settings_) gear?

**Comment by aschmidt74** [comment]
**Thank you!** That's a terribly important step in the setup ;) maybe a tiny little snapshot will help others greatly!
**Two more things:**
* can I add an `API-Key` in the cfg? I don't want to re-authenticate the app every time.
* Once a device is set to `expose=off` in eve it vanishes, as intended. But what if I changed my mind? Where would I get a hand on such devices in order to expose them again?

![28FC6A01-0634-4AD6-A041-F33390EB2F7A](https://user-images.githubusercontent.com/45806825/185925110-f7326f95-1923-45b0-899b-55ceaf87839d.jpeg)

**Comment by ebaauw** [comment]
> can I add an API-Key in the cfg? I don't want to re-authenticate the app every time.

No, you cannot, and you don’t need to.  It’s stored with the gateway accessory in `cachedAccessories`.

> Once a device is set to expose=off in eve it vanishes, as intended. But what if I changed my mind? Where would I get a hand on such devices in order to expose them again?

The gateway accessory gets a. _Device Settings_ service, where you can re-expose the device.  Clear _Expose Lights_, etc to get rid of these _Device Settings_.  That won’t affect the devies already exposed; it’s more like an “auto-expose new lights” settings.

**Comment by aschmidt74** [comment]
thank you once more for your support and explanation!
the whole plugin works like a charm - once its enabled properly ✅
