### ISSUE TITLE
support for rotary sensor of new hue tap dial

### ISSUE THREAD

**Issue by AlexAhrens** [ebaauw/homebridge-deconz#72]
are there any plans to add the support of the rotary sensor of the new hue tap dial switch to be used via deconz/phoscon and home bridge for dimming   ##e.g. purposes?

**Comment by ebaauw** [comment]
No plans.  Support was added in v0.0.18, exactly a month ago today.

**Comment by AlexAhrens** [comment]
okay, thanks for the info, than it's just me that I don't know how to expose it and make it useable within homebridge/homekit

**Comment by ebaauw** [comment]
The tap dial switch is exposed to HomeKit as six buttons, where button 5 (right turn)and 6 (left turn) are for the dial.  They issue _Single Press_ events every 400ms while rotating.

**Comment by AlexAhrens** [comment]
I see, that’s what I was looking for as info. Sadly,my setup only shows the 4 dotted buttons. (See attached screenshot from HomeKit, unfortunately in german. 

I‘m running HomeBridge v1.50, decent/phoscon v2.17.1 & HomeBridge-deconz v0.0.22

any idea where I might have a look to exposure the mentioned zwei rotary switches? 

![CD449C00-76EE-4207-A65C-39238A5D2D4A](https://user-images.githubusercontent.com/15001349/190895256-c9e38b40-8d7c-4f0e-9d43-51d74eb4003f.jpeg)

**Comment by ebaauw** [comment]
The deCONZ REST API should expose two `/sensors` resources for the Hue tap dial switch: a ZHASwitch for the buttons, and a ZHARelativeRotary for the dial.  It would seem the latter is missing; it was introduced in v2.18.0-beta, see https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6164.  I am surprised the ZHASwitch resource is exposed by v2.17.1.  Did you copy the DDF file yourself?

**Comment by AlexAhrens** [comment]
Thanks for the info, will look into it once 2.18. releases. 

I didn't copy any updates by myself nor did I ever switched to the beta update channel, I was surprised also. It even exposed the 4 buttons on v2.16.1 out of the box. 

<img width="649" alt="Bildschirmfoto 2022-09-18 um 16 41 16" src="https://user-images.githubusercontent.com/15001349/190912757-606981d9-d78f-4738-921b-07842a22b11a.png">
