### ISSUE TITLE
Energy consumption off by a factor of 10

### ISSUE THREAD

**Issue by oskarlindell** [ebaauw/homebridge-deconz#73]
Hi.

I have two smart plugs ("LUMI Adapter plug") that are showing incorrect energy consumption. Both are showing the consumption by a 10x factor, so for example 650 W is shown as 6500 W.

Is this something that is caused by a bug in homebridge-deconz or what could be the issue? 

/Oskar

**Comment by ebaauw** [comment]
What is the REST API showing?

**Comment by oskarlindell** [comment]
Using Node-RED and deconz-get I get the following result:

{"current":0,"lastupdated":"2022-09-13T13:09:31.190","power":6996,"voltage":0}

**Comment by ebaauw** [comment]
So this is an issue by the deCONZ REST API plugin.  It should report `state/power` in W.  Also, it shouldn’t expose `state.current` and `state.voltage` if the plug doesn’t report these.
