### ISSUE TITLE
all switches stopped working on the same time, needed to reconnect, one switch not been transferred from deconz to homebrigde (hue tap dial) after re-connection

### ISSUE THREAD

**Issue by AlexAhrens** [ebaauw/homebridge-deconz#74]

**Comment by AlexAhrens** [comment]
After some investigation and time it seems that periodically all switches (tested on hue dimmer switch, hue tap dial, Ikea trader switches and aqara smart buttons) discontinue to work. Homebridge (and apple's home app under iOS 16) shows that the buttons are indeed pressed, but no logging event occurs on the home bridge-deconz terminal. attached automatization's and lights don't respond to the button press event, simulating the press of said button in the home app works as expected.

**Comment by ebaauw** [comment]
Double-check your log settings, if the tile in the Home app bumps when you control the switch, Homebridge deCONZ is working, and you should see log messages in the Homebridge log.

I assume you’re using HomeKit actions to control your lights?  I recommend deCONZ rules to control Zigbee devices, and only use HomeKit automations for non-Zigbee devices.  deCONZ rules are faster, more reliable, and provide more functionality than HomeKit automations.

HomeKit automations (should) run on your home hub, not on your iPhone.  Make sure to update your AppleTV, HomePod, or iPod to the latest versions.  I’ve seen a lot of issues with iOS 16, but it looks like my setup has quieted down after a couple of days and is now working again.  Power-cycle your home hub(s), and check using `netstat` on the Homebridge server that it actually connects to the Homebridge (child bridge) server.

**Comment by AlexAhrens** [comment]
Thanks for the valuable input, I've doublechecked my setup and found the weak-spot: Apple TV running not the latest TVos Update. Was probably a strange behavior between ATV and the two HomePod Minis running in my setup, updated everything and works like a charm now. 

I'll look into deconz roles to simplify things :)
