### ISSUE TITLE
option to disable the custom accessories

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#76]
some lamps has custom effects, like the `LIDL Livarno Lux light strip` or the `Müller Licht Tint E27 Bulbs`.

i does not need the separate effect switches.
the existence ensures that I have to click twice every time I want to turn off the lights

Can you add a custom Resource to the light endpoint for each of this devices to disable the exposure of this switches?

https://github.com/ebaauw/homebridge-deconz/blob/0d08ca9600cb5eb8aca139de9c9d8a870e00f114/lib/Deconz/Resource.js#L452
https://github.com/ebaauw/homebridge-deconz/blob/0d08ca9600cb5eb8aca139de9c9d8a870e00f114/lib/Deconz/Resource.js#L471

**Comment by ebaauw** [comment]
> some lamps has custom effects

And the ZB3 Hue lights, when upgraded to the latest firmware.

> I have to click twice every time I want to turn off the lights

Select _Expose as separate tiles_ to prevent that.

> Can you add a custom Resource to the light endpoint for each of this devices to disable the exposure of this switches?

Technically I could, but I won’t.  The config settings through HomeKit doesn’t work out as I hoped, and I want to change that using the Homebridge UI instead.  Once I’ll have made that change, I can make the services for the dynamic scenes optional.
