### ISSUE TITLE
stopping deConz installation if make fails.

### ISSUE THREAD

**Issue by AssetBurned** [ebaauw/homebridge-deconz#8]
Hi,

I am likely at the wrong spot here, but if so I guess it is also the best place to redirect me.

If I understand it correctly you may run into the situation where the make command fails when you try to install the deConz package via "sudo hb-config" on a fresh install of the Homebridge raspberry installation.

Dresden-elektronik had a ticket open for that too https://github.com/dresden-elektronik/raspbee2-rtc/issues/13

So my suggestion is rather than continuing with the installation as nothing happen, to either stop the installation of the package. Or to provide more information at the end of the installation (e.g. in the blue screens of hb-config) on what happen or how to address this.

The Homebridge image I used is the latest image that is currently installed by the "Raspberry Pi Imager".

example logs (This is from the rerun of the install as i had some network issues):

pi@homebridge:~ $ sudo hb-config
Setting up for RaspBee...
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.5 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [250 kB]                                                                 
Fetched 13.5 MB in 1min 23s (162 kB/s)                                                                                                            
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
31 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
The following additional packages will be installed:
  libi2c0 read-edid
Suggested packages:
  libi2c-dev python-smbus
The following NEW packages will be installed:
  i2c-tools libi2c0 raspberrypi-kernel-headers read-edid
0 upgraded, 4 newly installed, 0 to remove and 31 not upgraded.
Need to get 27.8 MB of archives.
After this operation, 181 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf raspberrypi-kernel-headers armhf 1:1.20220120-1 [27.7 MB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libi2c0 armhf 4.2-1+b1 [10.4 kB]                
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf i2c-tools armhf 4.2-1+b1 [78.0 kB]              
Get:4 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian bullseye/main armhf read-edid armhf 3.0.2-1.1 [14.9 kB]
Fetched 27.8 MB in 39s (713 kB/s)                                                                                                                 
Selecting previously unselected package libi2c0:armhf.
(Reading database ... 45281 files and directories currently installed.)
Preparing to unpack .../libi2c0_4.2-1+b1_armhf.deb ...
Unpacking libi2c0:armhf (4.2-1+b1) ...
Selecting previously unselected package i2c-tools.
Preparing to unpack .../i2c-tools_4.2-1+b1_armhf.deb ...
Unpacking i2c-tools (4.2-1+b1) ...
Selecting previously unselected package raspberrypi-kernel-headers.
Preparing to unpack .../raspberrypi-kernel-headers_1%3a1.20220120-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1:1.20220120-1) ...
Selecting previously unselected package read-edid.
Preparing to unpack .../read-edid_3.0.2-1.1_armhf.deb ...
Unpacking read-edid (3.0.2-1.1) ...
Setting up libi2c0:armhf (4.2-1+b1) ...
Setting up read-edid (3.0.2-1.1) ...
Setting up raspberrypi-kernel-headers (1:1.20220120-1) ...
Setting up i2c-tools (4.2-1+b1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52260  100 52260    0     0  51691      0  0:00:01  0:00:01 --:--:-- 51742
Selecting previously unselected package wiringpi.
(Reading database ... 100070 files and directories currently installed.)
Preparing to unpack /tmp/wiringpi-latest.deb ...
Unpacking wiringpi (2.52) ...
Setting up wiringpi (2.52) ...
Processing triggers for man-db (2.9.4-2) ...
############################################################################################################################################ 100.0% #=O=#    #     #                                                                                                                                 
Archive:  /tmp/raspbee2-rtc.zip
6fabff2ee826c004dfb17eb4a5df115e262a0157
   creating: /tmp/raspbee2-rtc-master/
  inflating: /tmp/raspbee2-rtc-master/LICENSE  
  inflating: /tmp/raspbee2-rtc-master/Makefile  
  inflating: /tmp/raspbee2-rtc-master/README.md  
  inflating: /tmp/raspbee2-rtc-master/rtc-pcf85063.service  
checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
download rtc-pcf85063.c for kernel version 5.10 ...
curl -O --max-time 10 https://raw.githubusercontent.com/torvalds/linux/v5.10/drivers/rtc/rtc-pcf85063.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16326  100 16326    0     0  21710      0 --:--:-- --:--:-- --:--:-- 21710
build rtc module...
make -C /lib/modules/5.10.63+/build M=/tmp/raspbee2-rtc-master modules
make[1]: *** /lib/modules/5.10.63+/build: No such file or directory.  Stop.
make: *** [Makefile:17: build] Error 2
install rtc module...
make[1]: *** /lib/modules/5.10.63+/build: No such file or directory.  Stop.
could not install rtc module file (did you run make?)
make: *** [Makefile:42: install] Error 1
--2022-02-13 13:59:27--  http://phoscon.de/apt/deconz.pub.key
Resolving phoscon.de (phoscon.de)... 144.76.96.194
Connecting to phoscon.de (phoscon.de)|144.76.96.194|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1692 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                    100%[=====================================================================>]   1.65K  --.-KB/s    in 0s      

2022-02-13 13:59:27 (16.0 MB/s) - written to stdout [1692/1692]

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 http://phoscon.de/apt/deconz bullseye-beta InRelease [2,876 B]
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease                                                   
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease                         
Get:4 http://phoscon.de/apt/deconz bullseye-beta/main armhf Packages [733 B]           
Fetched 3,609 B in 5s (706 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
31 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:

**Comment by ebaauw** [comment]
> I am likely at the wrong spot here

Indeed, this is the repo for the Homebridge plugin to expose deCONZ to HomeKit.

> I guess it is also the best place to redirect me.

I never used it myself, but think `hb-config` is part of the Homebridge Raspberry Pi Image, https://github.com/homebridge/homebridge-raspbian-image.

**Comment by AssetBurned** [comment]
Great :-) thank you for pointing me in the right direction!
