### ISSUE TITLE
Expose Configured Name

### ISSUE THREAD

**Issue by JanLp** [ebaauw/homebridge-deconz#81]
Homebridge 1.5.1 > homebridge-deconz v0.0.27

Deleting the device under "Remove Single Cached Accessory" does not help

![Skærmbillede 2022-11-15 kl  14 07 30](https://user-images.githubusercontent.com/55313117/201927454-0200d811-7b59-4813-a16d-7f265da7eb53.png)
![Skærmbillede 2022-11-15 kl  14 06 54](https://user-images.githubusercontent.com/55313117/201927463-002d7b62-6a0d-4ca3-8359-b6af62ad73e8.png)
![Skærmbillede 2022-11-15 kl  14 14 27](https://user-images.githubusercontent.com/55313117/201928651-27419d39-9170-4184-9046-192126e6c7b0.png)

In Homebridge

![Skærmbillede 2022-11-15 kl  14 12 57](https://user-images.githubusercontent.com/55313117/201928335-c1cd05b0-9e17-4b83-8647-01434c9f7e84.png)

**Comment by ebaauw** [comment]
Not sure what the issue is?

> Deleting the device under "Remove Single Cached Accessory" does not help

Don't do that.  Clear _Expose_ on the _Device Settings_ service instead.

**Comment by JanLp** [comment]
> Not sure what the issue is?
> 
> > Deleting the device under "Remove Single Cached Accessory" does not help
> 
> Don't do that. Clear _Expose_ on the _Device Settings_ service instead.

Where should I do it? It's pretty messy, isn't it? The starting point must be that we use homebridge for homekit and not everything else. It's starting to get a bit illogical...

**Comment by JanLp** [comment]
You don't see the problem...under "Single Cached Accessory" is it named differently than everywhere else? I am left to chance ... and can only guess ...

**Comment by ebaauw** [comment]
Again: don't use that function.

I think it shows the accessory name, where "everywhere else" you're looking at the service name.  Only the service name is synced with deCONZ.  The only way to update the accessory name is to un-expose and re-expose the accessory.

**Comment by JanLp** [comment]
I've caught it ... but it simply doesn't make sense to the average user. It's messy, convoluted and involves a 3rd party app and knowledge of how homebridge deconz works. It doesn't make sense to the general user...sorry to say...but it's been a mess since the first release of homebridge-deconz

**Comment by ebaauw** [comment]
Yes, it is messy.  Homebridge deCONZ is still under development, and I'm trying to find the best way to support dynamic settings.  I could use resourcelinks on deCONZ, just like Homebridge Hue, but that isn't exactly friendly to the casual user either.  Ideally I want to expose these settings under the Homebridge UI, but that's quite a challenge, and considerably more work than I anticipated.

> It doesn't make sense to the general user

I'm sorry, but that's largely due to Apple, confusing the Home app with HomeKit, mixing "accessory" and "service" in the Home app, and not supporting all of HomeKit functionality in the Home app.

**Comment by JanLp** [comment]
You can say that... It doesn't change the fact that the average user can't figure out how homebridge-deconz works. It is not very user-friendly that users have to download a 3rd party app to get their devices in homekit. First he has to figure out homebridge, then he has to figure out homebridge-deconz to get his devices into homekit... I didn't think I was stupid myself... but it's pretty complicated. It should be isolated to homebridge ... And if it can't, then the introduction should be that NOTHING works without a 3rd party app and a thorough review.
