### ISSUE TITLE
Configurable syncing of resource and service name

### ISSUE THREAD

**Issue by torandreroland** [ebaauw/homebridge-deconz#83]
Could the syncing of service name with resource name introduced in v0.0.27 be made configurable? It looks like there is a character limit of 32 in Deconz, and I'm using longer name for services in HomeKit (naming convention of room name + accessory name).

**Comment by ebaauw** [comment]
What do you mean "configurable"?

**Comment by torandreroland** [comment]
Make it configurable that the configured name that is received from the deconz API is synced to the name of the service. I don't want the same name of the deconz resource synced to the service name since the former only supports 32 characters.

**Comment by ebaauw** [comment]
You mean you want to be able simply to disable the syncing?

**Comment by torandreroland** [comment]
Exactly

**Comment by ebaauw** [comment]
v2.20.x still exposes _Configured Name_, but no longer syncs it with the `name` on the deCONZ resource.
