### ISSUE TITLE
Problem with the HUE Plugin

### ISSUE THREAD

**Issue by peterpan869** [ebaauw/homebridge-deconz#85]
Hi guys,

im desperately trying to install the certified Philips HUE Plugin on my Box. In the past i never had problems with it. Now I always get this Error:

20:26:08yarn add v1.22.1120:26:08info No lockfile found.
20:26:09[1/4] Resolving packages...20:26:11[2/4] Fetching packages...
20:26:12error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-bonjour-hap-3.6.4-3770904941c6100d3887eca81488c5da250e9fb7-integrity/node_modules/bonjour-hap/.yarn-metadata.json: Unexpected end of JSON input".
20:26:12info If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/hoobs/yarn-error.log".
20:26:12info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

What can i do to fix it?
Appreciate your help

Thx, Peter

**Comment by ebaauw** [comment]
This is not an issue with Homebridge deCONZ.  Best contact Hoobs support, as suggested in the message.
