### ISSUE TITLE
Problem on connecting with Conbee2

### ISSUE THREAD

**Issue by platini76** [ebaauw/homebridge-deconz#86]
I have a raspberry with homebridge installed.
and another one with homeassistant where conbee is installed.
it is possible from homebridge read the key on th2 other raspberry?

172.30.33.2 is my key (from deconz homeassistant)
192.168.0.10 my homebridge
192.168.0.50 my homeassiatant

**Comment by platini76** [comment]
I have solved this with homeassiatant with the address 192.168.0.50:40485

but now I am trying to connect alexa.. and condee was not discovered

aanyone can help me?

**Comment by ebaauw** [comment]
Not here.  Best ask on the deCONZ forum.
