### ISSUE TITLE
Button battery status displays in Home+ as 'Arabic Numerals'

### ISSUE THREAD

**Issue by domdtyler** [ebaauw/homebridge-deconz#88]
Same setup as #87 

The battery level is exposed to HomeKit and is visible in Home+ through Advanced Features, but for some reason it selects the 'Label Namespace' field to display as a summary. I can't see any way to tell it to use the battery level instead!

**Comment by ebaauw** [comment]
Homebridge deCONZ exposes wireless controllers as per HomeKit specs:
- A (primary) _Label_ service with _Label Namespece_;
- A _Stateless Programmable Switch_ service per button or dial;
- A _Battery_ service.

What makes you think this is an issue with Homebridge deCONZ?  Do you have native HomeKit controllers or exposed by other plugins that Home+ displays differently?
