### ISSUE TITLE
Cannot update settings

### ISSUE THREAD

**Issue by pnewell** [ebaauw/homebridge-deconz#89]
Whenever I try to update the settings using the following:
```
curl -X PUT --json '{"logLevel": 1}' http://127.0.0.1:32833/gateways/00212EFFFF0A4FC1/settings
```
It doesn't work and I find the following in the Homebridge logs:
```
Phoscon-GW: ui request: PUT settings {"logLevel":1}
[31/12/2022, 15:15:54] [deCONZ] ui request 4: 501 Not Implemented
```

If it is helpful, if I do a GET on settings it returns the following:
```
{
  "expose": true,
  "groups": false,
  "heartrate": 30,
  "lights": false,
  "logLevel": 2,
  "schedules": false,
  "sensors": false
}
```

**Comment by ebaauw** [comment]
The latest published version still uses the _Gateway Settings_ and _Device Settings_ services to update dynamic configuration from HomeKit.  I wrote the Wiki as specs for my work in progress.
