### ISSUE TITLE
report unreachable devices

### ISSUE THREAD

**Issue by b2un0** [ebaauw/homebridge-deconz#90]
is it possible that this plugin report unreachable devices also to homekit as offline?

i seem to remember that this was already the case in the old `hue` plugin?!

for example: some of my aqara/xiaomi devices are randomly lost the connection

![image](https://user-images.githubusercontent.com/2155498/210180723-49e3a3be-4242-475c-9927-703c2f2b5d4e.png)

**Comment by ebaauw** [comment]
> is it possible that this plugin report unreachable devices also to homekit as offline? 

No, HomeKit doesn’t provide this functionality.  Both Homebridge Hue and Homebridge deCONZ set _Status Active_ to not active when the Hue bridge / deCONZ gateway reports `reachable` false`, but Apple’s Home app ignores that.

> i seem to remember that this was already the case in the old hue plugin?!

Homebridge Hue can optionally show a device as _Not Responding_.  I want to add that option to Homebridge deCONZ as soon as I’ve figured out how to deal with dynamic settings

> for example: some of my aqara/xiaomi devices are randomly lost the connection

No they didn’t.  Zigbee doesn’t do connections.  The _Not reachable_ status merely indicates that the gateway didn’t get a response when it last tried to contact the device, not whether the device is currently reachable.  End devices turn off their radio most of the time, and are almost never reachable.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2590 for details.
