### ISSUE TITLE
[Request] Wall Switch option

### ISSUE THREAD

**Issue by chris-rg** [ebaauw/homebridge-deconz#91]
Hello,

is it planned to support the "wall switch" option from the old Hue plugin?

<img width="513" alt="Bildschirmfoto 2023-01-04 um 18 03 26" src="https://user-images.githubusercontent.com/29870696/210610345-dfaa8fa7-3dd6-44c6-8682-8736b42b0fa8.png">

I'm still working on switching the dumb wall switches in my house so this option was very handy. Now I switched to homebridge-deconz and this is currently the only point that I found that is still a drawback compared to the old configuration.

Best Regards and thank you so much for your effort on this plugins

Chris

**Comment by ebaauw** [comment]
Yeah, is foreseen, but need to figure out how to deal with dynamic settings first.

**Comment by ebaauw** [comment]
In v0.1.9.

**Comment by chris-rg** [comment]
> In v0.1.9.

Nice, thank you for the update!

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-deconz/wiki/Dynamic-Configuration

**Comment by xBilyz3** [comment]
Unfortunately I get this error message. Maybe someone can help me. Could not find the solution myself.

curl -s -X PUT --json ‘{“wallSwitch: true“}’ http://127.0.0.1:46237/gateways/00212EFFFF06A0F1/accessories/7CB03EAA00AF52C0/settings
curl: option --json: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

<img width="1523" alt="Screenshot 2023-04-02 at 11 06 21" src="https://user-images.githubusercontent.com/52658352/229343551-7ab55ba6-4854-42c5-a4dc-cfa09d32f3b8.png">

**Comment by ebaauw** [comment]
See the Wiki.
