### ISSUE TITLE
Aqara Wall Switch - Decoupled Mode

### ISSUE THREAD

**Issue by Marfre888** [ebaauw/homebridge-deconz#92]
Hi,

I own a couple of Aqara wall switches (most with neutral wire (and 1 without neutral)), and all double rocker (H1). They are currently paired with an Aqara M2 hub. I originally ordered them so I can decouple some of the wired switches to be used as a 2way switch, while also having access to it in homekit. Unfortunately, this doesn't seem to be possible with the Aqara hubs.

Could you please tell him if the following is possible using deconz and a conbee 2 stick before I place an order?

1. Aqara Wall Switch, Not Decoupled - Switch Exposed to Homekit as a stateless switch
2. Aqara Wall Switch, Only 1 of 2 rockers decoupled - Relay permanently off (or on) and button presses act as a stateless switch
3. Aqara Wall Switch, Only 1 of 2 rockers decoupled - Debonz hub controls switching on/off different relay (corrected to different Aqara switch) while also exposing switch as a stateless switch

**Comment by ebaauw** [comment]
Whether you can decouple the buttons from the relays depends on the device hardware and firmware.  I know some Aqara models support this, others don't.

deCONZ exposes the relays as `lights` resources and the buttons as ZHASwitch `sensors` resources.  Homerbidge deCONZ exposes these as _Outlet_ and _Stateless Programmable Switch_ services respectively.  Homebridge deCONZ will support configuration which resources to expose, so you can hide the functions you don't want to use.

Independent from whether the buttons are coupled with the relays, you can use deCONZ rules to assign any actions to button events, controlling any Zigbee device in the same Zigbee network.  Alternatively, using HomeKit automations, you can assign any actions to button events, controlling any HomeKit accessory in the same home.  You need a home hub for this.

**Comment by Marfre888** [comment]
> Whether you can decouple the buttons from the relays depends on the device hardware and firmware. I know some Aqara models support this, others don't.
> 
> deCONZ exposes the relays as `lights` resources and the buttons as ZHASwitch `sensors` resources. Homerbidge deCONZ exposes these as _Outlet_ and _Stateless Programmable Switch_ services respectively. Homebridge deCONZ will support configuration which resources to expose, so you can hide the functions you don't want to use.
> 
> Independent from whether the buttons are coupled with the relays, you can use deCONZ rules to assign any actions to button events, controlling any Zigbee device in the same Zigbee network. Alternatively, using HomeKit automations, you can assign any actions to button events, controlling any HomeKit accessory in the same home. You need a home hub for this.

The Aqara switches I own support decoupling as I’m able to do it in the M2 hub. I did dig up some old thread from 2019 about supporting these switches, but couldn’t figure out if it was ever implemented. In fact in the compatibility chart my switches aren’t listed.

If deconz exposes the relay as lights and the switches as switches.. what is the relationship between the two?

**Comment by ebaauw** [comment]
>  what is the relationship between the two?

what do you mean?

**Comment by Marfre888** [comment]
> > what is the relationship between the two?
> 
> what do you mean?

If deconz exposes both the relay and the switch when they aren’t decoupled. Does the relay still turn on from the switch and also send a command to the stateless switch?

So deconz exposes both the lights and switch separate even if they aren’t decoupled? And can they be used in the rest api? It’s been a while since I’ve play with the rest api.

Does the Aqara hub have a rest api similar to the Philips Hue hub?

**Comment by ebaauw** [comment]
When coupled, the switch firmware switches the relay on button actions.  Technically, deCONZ cannot influence that.  As I said before, deCONZ exposes both the relays as well as the input buttons/rockers, whether they are coupled or not.

I’m not sure, but I don’t think the Aqara hub has a local API; their app seems to connect to the hub through their cloud server.

**Comment by Marfre888** [comment]
> When coupled, the switch firmware switches the relay on button actions. Technically, deCONZ cannot influence that. As I said before, deCONZ exposes both the relays as well as the input buttons/rockers, whether they are coupled or not.
> 
> I’m not sure, but I don’t think the Aqara hub has a local API; their app seems to connect to the hub through their cloud server.

Right, I was making sure I understood you correctly regarding switches being exposed.

So basically assuming I don’t have any lights connected to the relay, if I can’t decouple it I’ll just have a relay that clicks on/off. That’s an easy compromise.

The Aqara hub does do some processing locally it seems but does the complex automations on the cloud.
