### ISSUE TITLE
Device Settings and Gateway Settings services missing since update to v0.1.2

### ISSUE THREAD

**Issue by Hubsi3** [ebaauw/homebridge-deconz#96]
Hello @ebaauw 

Since the last update, I can't find any settings service using the eve app. Before I could use these services to change the log level and to disable specific sensors and lamps. Since the last update my logs again are flooded with single button press event (see #30) and also lamps I chose to disable are exposed to HomeKit again. 
So all these settings are lost? And also the settings services seem to be missing...

**Comment by Hubsi3** [comment]
Rollback to v0.1.1 did not solve the problem... Something seems to be wrong now, but everything has worked fine before the update to 0.1.2.

**Comment by ebaauw** [comment]
See the release notes: settings services have been removed.  Settings are now configured through a REST API provided by the plugin.  Eventually this API will be used by the settings dialogue in the Homebridge UI.

You might need to delete cachedAccessories when rolling back.

**Comment by Hubsi3** [comment]
Ok, thanks for clarifying that. I did read release notes of v0.1.2 and v0.1.1, but not of v0.1. So it's interesting why my settings were lost after the update to 0.1.2. But anyway, I could reconfigure it using CURL-requests to the api.

Maybe another little question: Are there any news on homebridge-hue2? I'm very excited for that :)

**Comment by ebaauw** [comment]
I want to reach a stable v1 of Homebridge deCONZ before starting to work on Homebridge Hue2.  No technical reason, just trying to keep my own mental sanity and not spreading my attention too thin.

**Comment by Hubsi3** [comment]
Ok sounds good and makes sense. Thank you for your work. We can close here :)
